### ISSUE TITLE
FE: Hotswap models in In-Game Preview

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#1192]
Currently it looks like the rendering context is completely reset when a new card is selected. It would be much faster to retain the rendering context and environment, and hotswap the model.

**Comment by avaer** [comment]
This is true, and probably a good idea.

However, the problem is that old NFT state can linger unless we do a reset, so resetting the context here is the safe option.

I'd like to explore ways to speed up engine load, which would solve a lot of this concern, and which I'm convinced can be massively improved (possibly with caching, building to tree shake, or getting rid of dependencies, none of which have been tried yet).

**Comment by soulofmischief** [comment]
Ok, we can explore that avenue first, that's low hanging fruit
