### ISSUE TITLE
Art: Avatar review

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1299]
This issue is for review/glitch tracking of new avatars.

**Comment by avaer** [comment]
![unknown](https://user-images.githubusercontent.com/6926057/120868385-f651fd00-c561-11eb-9e4d-014289779b0b.png)

This isn't a big deal but the eye bones seem to be pointing  not forward by default.

**Comment by avaer** [comment]
I can't pose any emotions on this one until the morphs are fixed, since the skin above eyes cannot actually raise/lower the forehead, which nullifies most emotions.

![image](https://user-images.githubusercontent.com/6926057/120869694-03242000-c565-11eb-8cf9-cfe168ad96e1.png)

**Comment by avaer** [comment]
Mouth internals do not conform to face morphs. This is with I + E.

![image](https://user-images.githubusercontent.com/6926057/120869826-4a121580-c565-11eb-9d17-36a55c9e5dee.png)

**Comment by avaer** [comment]
Similar eye morph problems on gear: 
![image](https://user-images.githubusercontent.com/6926057/120869949-a2491780-c565-11eb-8581-b0a4df2aa495.png)

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/120870379-c9ecaf80-c566-11eb-9ab7-5961710520f1.png)

**Comment by Vianvolaeus** [comment]
The morph issues are because the avatars in their current state are seperated into meshes defined by the material they are using. If you look at the mesh for the brows, lashes, etc, they will also have shapekeys for the expressions. 
Activating these on each mesh should result in a visually correct morph.

The meshes can also be selected and merged into a single object - we can split them again later if needed. (select all relevant meshes, ctrl+J) This means you would only need to control one shapekey for expressions, rather than values on several objects.

**Comment by Vianvolaeus** [comment]
> eye bones seem to be pointing not forward by default.

Yes - VRoid's heads have this bone orientation by default. Using free rotation and Individual Origins pivot-point should work fine, so long as X-mirror is disabled. 

The bones have this orientation since they are the 'paper' 2D eyes, they effectively need to rotate on a radius larger than the head itself, so the bones are offset to achieve this.

Commonly the rotation of the bone's head/origin is used and the tail is ignored.

If it is preferable to have the eye bone tails facing forward, I can still do that.

**Comment by Vianvolaeus** [comment]
> This is with I + E = 1
 
 Multiple viseme shapekey values shouldn't be stacked like this. In some cases it may visually look okay, but more often than not, going past 1 on multiple shapekeys will result in something that looks bad or glitchy, since vertices will be moving far past their intended final position.
 
 > It's hard to experiment further since the morphs clip into the face due to the above issues
 
 Some of the shapekeys the VRoid outputs are _extreme!_ Luckily, we can actually limit the maximum value of any shapekey within Blender, and any exported model from Blender will also respect that value!
 I believe Studio also has some more shapekey editing tools as well - we can go back there and limit / change certain things now. 
 
 The brows are usually the main offender - here's an example of the value limit, off vs on: 
![image](https://user-images.githubusercontent.com/80061436/120896945-b0596f80-c61b-11eb-8162-07a52c58850a.png)
![image](https://user-images.githubusercontent.com/80061436/120896960-c49d6c80-c61b-11eb-9986-2e83f38d898d.png)

**Comment by Vianvolaeus** [comment]
> Something is busted on the finger UVs.

This one is a bizarre one. Will take a look, since this isn't a problem in Substance Painter, but for whatever reason *is* present in Blender. Will check the texture mapping in Blender, potential exporting issues, etc.

**Comment by avaer** [comment]
> The bones have this orientation since they are the 'paper' 2D eyes, they effectively need to rotate on a radius larger than the head itself, so the bones are offset to achieve this.

Ok thanks that clarifies it.

> If it is preferable to have the eye bone tails facing forward, I can still do that.

Nah, I can do the prerotation. It just seemed weird to me.

**Comment by avaer** [comment]
> Multiple viseme shapekey values shouldn't be stacked like this. In some cases it may visually look okay, but more often than not, going past 1 on multiple shapekeys will result in something that looks bad or glitchy, since vertices will be moving far past their intended final position.

I realize that, I just like to cheat to get the effect I'm looking for. Range is _probably_ the better tool though; thanks for showing where that is in Blender.

**Comment by avaer** [comment]
> The meshes can also be selected and merged into a single object - we can split them again later if needed. (select all relevant meshes, ctrl+J) This means you would only need to control one shapekey for expressions, rather than values on several objects.

Got it, thanks. I don't think I've ever worked with such a split file with same morphs on many meshes so I was confused.

**Comment by Vianvolaeus** [comment]
> Got it, thanks. I don't think I've ever worked with such a split file with same morphs on many meshes so I was confused.

Side effect from how VRoid models are constructed, and the texture baking process for SP. (since there's floating geometry, it projects onto other parts of the mesh and bakes incorrectly) 
Also handy to have parts seperated while we're still live concepting. 
Final models won't need to be separated like this at all, can be merged no problem 👍

**Comment by Vianvolaeus** [comment]
Citrine and Kanji now have updated versions with better rigging and merged meshes so they can be posed (with expressions) better than before. They've also been optimized a little and cleaned up in their .blend files. 

I will update the rest in the same manner as I continue the fixes in #994 , where the the finalizing is currently being tracked.

**Comment by avaer** [comment]
One quick thing I noticed when posing: can we reduce the chest on Gear to make it more boylike/ambiguous in a silhouette? It's too obvious right now, but the rest of the design is great.

Gear is probably the only avatar where this applies.

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/122436028-657f1680-cf90-11eb-90f9-901272144a20.png)
Some minor reductions in proportions, as per previous suggestions, and also some editing towards ambiguity

**Comment by Vianvolaeus** [comment]
Additional cleanup and fixing has been carried out across all avatars. Files in drive updated.

@plankatron is going to save poses to a Blender Pose Library which we will be able to instantiate across all avatars via file appending - meaning that any pose made or tested with can be saved to this pose library, and then brought in to the avatar .blend file for usage.

This works since all avatars share identical naming convention and hierarchy. (the VRoid base armature)

As per request, I've prepared a workflow for exporting an armature pose alongside a shapekey facial expression. This includes your preferred method of combining different shapekeys to create a facial pose, @avaer, as well as using the preset facial expressions. 

I will attach it in the following comment since it's a bit lengthy.

**Comment by Vianvolaeus** [comment]
Skinned gltf to static w/ shapekey expression workflow:

(CATS Plugin used. Very useful here for applying poses and shapekey editing etc.)

Pose Character w/ armature in Blender.

Apply as Rest Pose in CATS n-panel. Character will now be fixed in the pose that they were posed in. 

Use existing expression, or, if making a custom one from a mix of existing, create a New Shape From Mix in the dropdown menu on the right of the Shape Key window.

Select this new Shape Key (Key [#])
Make sure it's value is set to whatever you wish it to apply as, and check the second box (view shapekey value in viewport)

Select all required objects in the viewport (can select all in viewport with A)

Export as gltf / glb with the following settings: 

Include > Limit to Selected Objects

Animation > Shape Keys > Uncheck Shapekey Normals / Tangents [Keep Shape Keys checked!]
// this is so surface normals don't look terrible for shapekeys

![image](https://user-images.githubusercontent.com/80061436/122964561-4cef7180-d37f-11eb-9ec2-c9640f9170f2.png)
