### ISSUE TITLE
megasword animation 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1302]
thread for animation of the megasword . 

https://user-images.githubusercontent.com/5592454/121061294-a5c0e680-c791-11eb-984b-3f1e55a21487.mp4

**Comment by avaer** [comment]
Can we do this fold without "breaking the laws of physics"? E.g. have it based on hinges, origami (or rather kirigami).

What stands out here is the scaling and detachment of parts, which gives a lot of creative liberty but kind of makes the whole thing dismissible as "magic".

The effect that I had in mind is more "someone put a lot of work in to design this technology".

**Comment by avaer** [comment]
https://cdn.discordapp.com/attachments/498315766509338636/851579125998682173/megasword0001-0060.mp4
https://cdn.discordapp.com/attachments/498315766509338636/851579135595642951/megasword0001-0060_1.mp4
https://cdn.discordapp.com/attachments/498315766509338636/851579145350938654/megasword0001-0070.mp4

**Comment by plankatron** [comment]
i might add some weight to each fold but how about this?
https://user-images.githubusercontent.com/5592454/121111107-52c05100-c7dc-11eb-8186-299fb844bbe4.mp4

**Comment by plankatron** [comment]
@madjin wanted to try a tweak to the animation 

https://user-images.githubusercontent.com/5592454/121117329-f5c99880-c7e5-11eb-9f5b-484ba820ec0b.mp4

**Comment by avaer** [comment]
I think the direction in https://github.com/webaverse/app/issues/1302#issuecomment-856381248 works best, it just would need to be completed and fleshed out. (e.g. a closed sword shouldn't have jagged edges sticking out)

Ideally the final shape is compact and handheld, like a lightsaber, rather than a big chunk as big as your head. Perhaps the last phase could be a shrinking like a pokeball?

**Comment by plankatron** [comment]
how bout this? 

https://user-images.githubusercontent.com/5592454/121281906-b616b580-c8a6-11eb-888b-d262bdc4c7c1.mp4

**Comment by avaer** [comment]
Looks like the right direction; maybe a couple more steps of crunching so only the handle remains?

I'm also curious what the geometry looks like from other angles.

**Comment by plankatron** [comment]
got it , i left the rock as you mentioned the poke-ball concept 

https://user-images.githubusercontent.com/5592454/121376850-de86ca00-c90f-11eb-96fa-7c4fea8960cf.mp4

**Comment by plankatron** [comment]
going to tweak the opening animation tonight, not happy with it

**Comment by avaer** [comment]
I think we should still keep connectivity for the final part.

Maybe instead of the pokeball approach we can flatten the pieces around the handle like a rapier?

![image](https://user-images.githubusercontent.com/6926057/121466058-c0a77c80-c984-11eb-8ba3-beb5666068b5.png)

Piggy backing off of that idea, it might be doable so the final folds slide it into the shape of a flower, with the stick like things being the tendrils.

The point is so that it is easily recognizable in the folded form. Having it be just a handle would be recognizable, but so would if the final shape were an interesting shape.

**Comment by plankatron** [comment]
hows this ? tried to make a sort of hilt out of some of the elements 

https://user-images.githubusercontent.com/5592454/121599442-0c076c80-ca11-11eb-93b1-71642e0499f3.mp4

**Comment by plankatron** [comment]
small tweak but it kept bothering me so had to do it !

https://user-images.githubusercontent.com/5592454/121929421-2f7f2f80-cd0f-11eb-8166-48f8f2c31fe6.mp4

**Comment by madjin** [comment]
Couple new variations of the sword made, figured I can throw them here

![image](https://user-images.githubusercontent.com/32600939/122629662-8f5d3980-d073-11eb-818f-c8c7bb1615d2.png)

![image](https://user-images.githubusercontent.com/32600939/122629665-9421ed80-d073-11eb-9364-bf2b8b05d92d.png)

**Comment by madjin** [comment]
feedback: would like to change the trigger on the hilt, some inspiration:

![2021-06-19-02:46:32](https://user-images.githubusercontent.com/32600939/122635689-3fde3400-d09a-11eb-9625-f3060ece773c.jpg)

![2021-06-19-04:04:24](https://user-images.githubusercontent.com/32600939/122635708-5d130280-d09a-11eb-9bae-37b3053a64cb.jpg)

![image](https://user-images.githubusercontent.com/32600939/122635716-643a1080-d09a-11eb-964f-6980605cdd57.png)

https://www.google.com/search?q=snk+sword&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiOsdDzjKPxAhVMBs0KHdZzCjAQ_AUoAXoECAEQAw&biw=1821&bih=869#imgrc=i5A_4INql3GhaM

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/122964806-8a53ff00-d37f-11eb-87f3-1d0d243642be.png)

I've added a trigger that works in tandem with the blade activation shapekey here, across all variations of the sword.

I omitted the gun triggers since I believe that is for ejecting the blade itself (I haven't seen AoT, but that is what was demo'd from what I could find) and instead repurposed the design as a single finger trigger and handguard.

**Comment by Vianvolaeus** [comment]
This should become part of the new megasword design process at #1335. Closing this one.

**Comment by avaer** [comment]
Btw this sword is still great even if it’s not the mc BFS. It can be used for other things. For example, it could be a rival’s BFS.

**Comment by Vianvolaeus** [comment]
It could serve as weapon wielded by a Great Filter antagonist / defender - it's huge, blocky and square. Could make a good weapon for someone blocking the group or MC's progress.
