### ISSUE TITLE
Art: Bow

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1312]
The bow is a projectile type weapon type NFT.

**Inspiration**

Designs that are based on an insect or organic nature inspired are most interesting.

![image](https://user-images.githubusercontent.com/32600939/121959230-834f4000-cd32-11eb-8fe6-781f7adad307.png)

- https://www.pinterest.ca/pin/472103973414756728/
- https://www.pinterest.com/pin/107242034864061011/
- https://www.pinterest.ca/pin/698269117208327550/

Fair warning: super intricate designs a problem may arise of "cosmetic creep" in which the art team will have to consistently outdo themselves to keep sales steady.  This leads into more extreme and outlandish cosmetics which no longer feel thematic to the world.

Also, it would be nice for future season artists to have some kind of standard reference model template to remix.

## Current designs

Each 6k tri on average

![image](https://user-images.githubusercontent.com/32600939/121960069-9dd5e900-cd33-11eb-9058-dd7bf7983609.png)

![image](https://user-images.githubusercontent.com/32600939/121960086-a29a9d00-cd33-11eb-800e-dcba8287fa2d.png)

![image](https://user-images.githubusercontent.com/32600939/121960096-a62e2400-cd33-11eb-87e4-f4300ab6a6dd.png)

![image](https://user-images.githubusercontent.com/32600939/121960194-c2ca5c00-cd33-11eb-8b1f-177fc2a24366.png)

**Comment by avaer** [comment]
This looks good, but I'm not sure it's unique enough for the main weapons requirements.

I would describe this as "a cool bow" -- but for example with the beetle bow I would say it's "a bug that is also a bow", which is more interesting and vivid conceptually.

One way to do it might be to make the bow out of a materials that bows would not be made out of.

Also I think if we are going with greens and pinks it would be better to lean into earthy textures rather than neon/energy ones.

**Comment by Vianvolaeus** [comment]
I personally think the enchanted branch / vine type weapon feels a bit generic. Most bows by default are made of organic materials, so I think that a bow made from something completely different is much more interesting.
Agreed with the idea of making an item work out of something atypical.

The beetle one is an interesting idea. We could make something like the spines of the bow being a stag beetles mandible? Could make for an interesting animation... could use some kind of iridescent material like some beetles have. 

Path of Exile has a few different weapons and items made from odd, improvised and thematic materials for the dark fantasy setting: 

![image](https://user-images.githubusercontent.com/80061436/122064019-b2c08400-cde8-11eb-9eff-1f36e7b7f75f.png)

**Comment by avaer** [comment]
I like how disgusting it is to have ribs as the bow.

You could tie it together with flowers or something for extra contrast.

![image](https://user-images.githubusercontent.com/6926057/122082297-e4782180-cdcd-11eb-9ece-fa8fc6555e7c.png)

**Comment by GaladWarder** [comment]
Other than being epic and organic, are there any other requirements for the design?

If it's for S1, I'm assuming it needs to be stylized in the sort of bright, chunky style we're currently using, anything other than that?

Like, is it serving a specific purpose in the trailer/is it for a specific character's aesthetic/is it meant to be good/evil/neutral, etc...

Even a design like a rib bow can go a lot of different directions depending on what it's purpose is

**Comment by GaladWarder** [comment]
Some other options/ideas, I tried to pull in Dream's initial shape and combine it with some of the keywords you listed. 

If any of these are clicking, let me know and I can either refine or iterate

![WEBAVERSE_BowDesigns_V2](https://user-images.githubusercontent.com/29031531/122213040-19be6580-cedb-11eb-81c1-2ebe7b551732.jpg)

**Comment by avaer** [comment]
Wow, thanks for the palette!

I think the astmmetries and folds works best and you have some nice examples.

I'm not sure epic is the best descriptor; the featured design is quite epic.
 
But it's epic in the sense of "dwarves toiled for generations to craft this bow with magical perfection and now it's yours" rather than "Kylo ren's such a badass he made a yolo lightsaber and it is very unstable and has cross guard vents".

It is informative that in this description I deferred lightsaber's qualities to someone's personality.

Having it made up of body parts of creature you wouldn't sympathize with, but everyone is familiar with, like an invertebrate, provides a visceral counterpoint while making it hard to dismiss as "just another magical bow". It makes you think who would rip up a bug and why. And you would just tell that story rather than saying "it's a nice bow", which would be selling any bow short.

Other good features are anything that is floppy, windy, juicy, or dynamic, that would make you want to fiddle with this you saw it on the shelf (this might be the case in vr). It's a bit different than having something pristine, beautiful, solid, colorful, or even epic.

I'm pretty sure I've said this elsewhere but a lot of my thinking is around whether you can easily draw it, and or replicate it with home made materials while still carrying across the idea.

I don't expect this to ever happen but it is a good litmus test for a simple impactful design of objects for the brand.

![image](https://user-images.githubusercontent.com/6926057/122265691-04c7df00-cea7-11eb-8c13-452cb2f015e6.png)

![image](https://user-images.githubusercontent.com/6926057/122265705-08f3fc80-cea7-11eb-96f8-19ad6fe83e86.png)

![image](https://user-images.githubusercontent.com/6926057/122265711-0beeed00-cea7-11eb-817e-c280ef2a04bb.png)

**Comment by GaladWarder** [comment]
Makes sense, I'll do an iteration pass on the three designs you pulled out as soon as the logo's done!

You mentioned tying it to a someone's personality - are you looking for a tie to one of the existing characters, or more of just an implied story/implied personality from whoever made it?

**Comment by avaer** [comment]
> are you looking for a tie to one of the existing characters, or more of just an implied story/implied personality from whoever made it?

Ideally yeah, that's the point of all of these weapons. My only opinion is that the sword already makes sense to me with gear/#3.

**Comment by avaer** [comment]
But also feel free to make up a story or personality -- the point is that if you can, it's a good sign about the design.

**Comment by GaladWarder** [comment]
Had some time today, so took a crack at some more bow designs - these are all based off of the asymmetric model/sketch and the feedback. 

**I have a ton more ideas**, these are just what I had time for today. I'll keep cracking away at these anytime I can, just let me know if there are any that really click and you want me to iterate on.

I'm thinking for these designs, the bug parts have all been used to enhance the bow - either through the limbs having better elasticity than wood, or by adding a melee aspect to the weapon.

I also chunked together the materials a bit to simplify the designs.

![WEBAVERSE_BowDesigns_V3 copy](https://user-images.githubusercontent.com/29031531/123257892-531f5280-d525-11eb-9180-7383500381cd.jpg)

**Comment by Vianvolaeus** [comment]
This should probably be backburner (and checked to see if still required) since the character weapon requirements have been updated.
