### ISSUE TITLE
Art: Quality check assets

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1316]
Go through the various assets related to drops and check for:

Optimization:

* can triangles be reduced without degrading quality?
* how many materials and are the textures optimized?

Aesthetic:

* Load into [GLTF viewer](https://gltf-viewer.donmccurdy.com/) to check for errors 
* Is transparency working properly?
* Are there any noticeable defects?

**Comment by madjin** [comment]
1. Home island

Before: 19.6 MB
After: 7.2 MB

Triangles: 88.8k -> 73k

![image](https://user-images.githubusercontent.com/32600939/122658389-8f743c80-d13a-11eb-9016-887448377113.png)

![image](https://user-images.githubusercontent.com/32600939/122658431-3eb11380-d13b-11eb-8adb-cbf0ce492a42.png)

![image](https://user-images.githubusercontent.com/32600939/122658550-aa47b080-d13c-11eb-9ab9-089b366c443c.png)

Optimized home island, most data was in the textures.

**Comment by madjin** [comment]
2. Citadel

Before: 31.3 MB
After: 12.8 MB

Tri: 188k -> 177k

uploaded to drive

![image](https://user-images.githubusercontent.com/32600939/122658652-f1827100-d13d-11eb-9a17-d81fd122a8cb.png)

![image](https://user-images.githubusercontent.com/32600939/122658770-16c3af00-d13f-11eb-9e4c-de6fab8b46f0.png)

**Comment by madjin** [comment]
3. Citadel Interior

Before: 40.2 MB
After: 10.3 MB

Tri: 114k

Looks nice in blender but the export is messed up. Most the data was 1 oversized texture.

![image](https://user-images.githubusercontent.com/32600939/122658853-08c25e00-d140-11eb-83fd-290e2ddccd52.png)

![image](https://user-images.githubusercontent.com/32600939/122658852-03fdaa00-d140-11eb-8043-88f097693890.png)

edit* fixed

![image](https://user-images.githubusercontent.com/32600939/122660446-a709f000-d14f-11eb-845f-2d24740dcc6b.png)

uploaded to drive

**Comment by madjin** [comment]
4. Green hill inspired world

Before: 11.6 MB
After: 9.77 MB

Tri: 114k


Noticed the palm tree leaves are missing transparency, fixed via editing the shader in blender.

![image](https://user-images.githubusercontent.com/32600939/122661450-7084a300-d158-11eb-8f57-09107afab5e3.png)

Some other materials had issues. Just did a fresh glb export and it looks pretty flawless now.

![image](https://user-images.githubusercontent.com/32600939/122661911-1a662e80-d15d-11eb-8fae-2d8340460191.png)

uploaded glb to drive

**Comment by madjin** [comment]
5. Scifi Club

Before: 8.07 MB
Tri: ~114k

Just want to say how beautiful this build is, haven't really had time to check it out. Also it is well optimized already. Great work.

![scifi-club](https://user-images.githubusercontent.com/32600939/122662084-58b01d80-d15e-11eb-917f-141468e1e61e.png)

![image](https://user-images.githubusercontent.com/32600939/122663637-1db3e700-d16a-11eb-89f3-9ed27970ec18.png)

**Comment by madjin** [comment]
6. Kiiba Pets

**Blob**

Everything looks good. 2048x2048 texture for blob seems high but other than that blobs are great.

![image](https://user-images.githubusercontent.com/32600939/122663799-13461d00-d16b-11eb-91a6-3dcd6c46133b.png)

**Ghost Fox**

Everything good, same as blob re: 2048x2048 textures but that can be changed later. Always good to start high.

![image](https://user-images.githubusercontent.com/32600939/122663850-83ed3980-d16b-11eb-9fb0-ff7ea5162436.png)

**Dragon**

Some of the textures are very simple yet high file size. I optimized the textures to a new blend file and uploaded to drive.

Before: 10.3 MB
After: 1.6 MB

![image](https://user-images.githubusercontent.com/32600939/122663932-0f66ca80-d16c-11eb-9baa-48a4ff09aeb6.png)


![image](https://user-images.githubusercontent.com/32600939/122663888-ab440680-d16b-11eb-8751-e1a988736feb.png)

**Comment by madjin** [comment]
7. Backpacks

Before: 14.3 MB
After: 1.6 MB

Tri: 6.5k -> 3.4k

![image](https://user-images.githubusercontent.com/32600939/122672519-dba29980-d199-11eb-89cf-86aa9e4958a7.png)

![image](https://user-images.githubusercontent.com/32600939/122672755-3dafce80-d19b-11eb-8a29-d2b39ad2522d.png)

Before: 9 MB
After: 1.7 MB

Tri: 12.3k -> 10.7k

![image](https://user-images.githubusercontent.com/32600939/122672801-6a63e600-d19b-11eb-8326-e47eed01580f.png)

![image](https://user-images.githubusercontent.com/32600939/122672967-510f6980-d19c-11eb-88a5-27adc418aa71.png)

Both uploaded to drive

**Comment by madjin** [comment]
8. Hovercraft

Before: 4.6 MB
After: 964 KB

Tri: 10.8k

![blender_a7ZuJzJjm4](https://user-images.githubusercontent.com/32600939/122673074-d3982900-d19c-11eb-9e37-dedd050a29fc.png)

![image](https://user-images.githubusercontent.com/32600939/122673173-499c9000-d19d-11eb-9ed9-a8efa1e86db2.png)

Great model, only 1 material, Uploaded to drive.

**Comment by madjin** [comment]
9. Scythe

Before: 5.4 MB
After: 1.36 MB

Tri: 15.6k -> 14.3k

![image](https://user-images.githubusercontent.com/32600939/122673481-a3ea2080-d19e-11eb-9dd1-0e6545c5d91d.png)

![image](https://user-images.githubusercontent.com/32600939/122673506-bcf2d180-d19e-11eb-8986-1c3f7f937350.png)

This too is only 1 material. If we want to tweak some of the items on the scythe we'd have to do so manually in the future. Uploaded to drive.

**Comment by madjin** [comment]
10. Hoverboards

Before: 1 MB
After: 464 KB

No underside to this

![image](https://user-images.githubusercontent.com/32600939/122673858-8322ca80-d1a0-11eb-8c2c-f07d66001560.png)

Before: 1.8 MB
After: 800-900 KB

Tri: 8.6k

Contains undersides to the board. I stopped at board 3 because I don't think we settled on the design yet. Boards 0-3 been uploaded to drive.

![image](https://user-images.githubusercontent.com/32600939/122674580-c3d01300-d1a3-11eb-99b8-6910d260b15d.png)

Here's the github issue: https://github.com/webaverse/app/issues/1292

**Comment by madjin** [comment]
11. Hoverboards

Silver hoverboard

Before: 57 KB
Tri: 1.3k

No need to optimize this, its good already.

![image](https://user-images.githubusercontent.com/32600939/122674733-71432680-d1a4-11eb-89e6-9ae08c7310f4.png)

Retro

Before: 424 KB
Tri: 2.3k

It's already optimized

![image](https://user-images.githubusercontent.com/32600939/122674793-ac455a00-d1a4-11eb-9e7f-f948967d6b4f.png)

I'm not going to touch the keyboard one because we haven't decided on it yet. All these are on drive.

**Comment by madjin** [comment]
12. Pistol

Before: 14.5 MB
After: 727 KB - 1 MB

Tri: 3.3k (plain) - 8.7k (x2 customization)

Noticed that when I exported the file was 14 MB, reduced a14MB 4k resolution png for the texture to 2k resolution jpg. Quality looks the same. Note: there are 3 color variations of this texture also, I optimized 1.

![image](https://user-images.githubusercontent.com/32600939/122675225-799c6100-d1a6-11eb-9973-9ae888cd2116.png)

Uploaded new .blend to drive.

**Comment by madjin** [comment]
13. Megasword

Before: 4.5 MB
Tri: 10k

This asset isn't finished yet (still needs new handle) but one way to optimize would be to convert the textures to jpg, alpha isn't needed and it will save about 3 MB.

![image](https://user-images.githubusercontent.com/32600939/122675540-e5cb9480-d1a7-11eb-9bc3-1465ed829575.png)

**Comment by madjin** [comment]
14. Kachete

Before: 9.1 MB
After: 2 MB

Tri: 598

The base texture needs to stay png because of the alpha layer for making the thin emissive laser line of the blades edge. Also I don't think this weapon needs a normal map, looks better without one actually.

![image](https://user-images.githubusercontent.com/32600939/122675931-b9b11300-d1a9-11eb-9447-79da8493254a.png)

Uploaded new blend and glb to drive.

**Comment by madjin** [comment]
15. Rifle

Before: 4.7 MB
After: 1.1 MB

Tri: 10.8k

Straightforward optimization, single material. It'd be nice to reduce some triangles in places, not sure how we would like to cut it.

![image](https://user-images.githubusercontent.com/32600939/122676199-fb8e8900-d1aa-11eb-8c4f-048703da8edf.png)

![image](https://user-images.githubusercontent.com/32600939/122676275-6f309600-d1ab-11eb-85c0-50c6ee99c3cb.png)

Uploaded original and optimized version to drive.

**Comment by madjin** [comment]
16. Goggles

Before: 2.44 MB
After: 389 KB

Tri: 1.6k 

There are 3 textures (diffuse, normal, metallic). Didn't touch any triangles. There's no transparency for the goggles glass in original, if that matters.

![image](https://user-images.githubusercontent.com/32600939/122676615-cbe08080-d1ac-11eb-813c-a27fdafa2606.png)

![image](https://user-images.githubusercontent.com/32600939/122676624-da2e9c80-d1ac-11eb-949d-300cb3045f74.png)

**Comment by madjin** [comment]
17. Meta Hood

Sithlord has been exporting glbs of the houses in Meta hood, the inside and outside are modeled cleanly. Here's the open issue for meta hood: https://github.com/webaverse/street-assets/issues/5

Before: 2 MB
Tri: 3.5k

![image](https://user-images.githubusercontent.com/32600939/122676825-ab64f600-d1ad-11eb-9c0c-c3beeda2be66.png)

Before: 2.7 MB
Tri: 7.4k

![image](https://user-images.githubusercontent.com/32600939/122676756-604ae300-d1ad-11eb-82ad-ab41f8fd8b12.png)

Not much to optimize besides creating a texture atlas for each. For now I uploaded to drive. There is a few more in the collection that haven't been exported yet.

**Comment by madjin** [comment]
Status report:

I reduced the file size from 187.8 MB -> 55.7 MB across 16 assets without sacrificing any visual quality.

Remaining / WIP assets:

- Bow
- Characters + props
- Megasword
- Discord bot avatar
- Tactical guitar

**Comment by Vianvolaeus** [comment]
For reference: any assets I've made can have their resolution and file format adjusted at texture export. This is a standard feature of Substance Painter, the resolution can be changed on the fly, and can use very high resolution bakes , but export things down to 2k, 1k, all the way down to 128. 

Since this is done at the *project* level rather than directly influencing textures, we can go back and change anything non-destructively. 

We should also be using packed ORM maps if possible (or required) under glTF standards. This will save texture loads per material.

We also should consider the need for mipmaps and LODs in this process. Texture dilation between the gaps can increase file size (by a small amount), but on size heavy maps like normals, etc, they can add up.

Notes:

Generally speaking I optimize at the end of the process once designs, color schemes, etc are finalised. 

Optimizing too heavily on things like character assets *initially* can be detrimental, and in the case of the bases we are using, can interfere with the bake process. 
That said I do aim to have some idea of what's going to be optimized going in. Any alpha / transparency dependent materials should be atlassed together, for example.

**Comment by madjin** [comment]
18. Bot

Before: 2.38 MB
After: 522 KB

Tri: 1126

![image](https://user-images.githubusercontent.com/32600939/122829267-cb331180-d2b4-11eb-9d40-fd1e7f942f5e.png)

The nodes need to be fixed in the main blender file, I removed most for a GLTF export.

![image](https://user-images.githubusercontent.com/32600939/122829574-2c5ae500-d2b5-11eb-8231-1a11e42c9dd0.png)

There are 3 materials.

![image](https://user-images.githubusercontent.com/32600939/122831948-a0e35300-d2b8-11eb-9cf6-6879e9ef185b.png)

![image](https://user-images.githubusercontent.com/32600939/122832462-5a422880-d2b9-11eb-8213-7bef1ebfa580.png)

Uploaded to drive

**Comment by avaer** [comment]
Here are the assets that need changes/redo and are not worth optimizing yet (it is the majority unfortunately):

![image](https://user-images.githubusercontent.com/32600939/122658652-f1827100-d13d-11eb-9a17-d81fd122a8cb.png)

This one needs a retexture to not complete green. This was agreed on in a past meeting.

![image](https://user-images.githubusercontent.com/32600939/122658853-08c25e00-d140-11eb-83fd-290e2ddccd52.png)

Removing the checkerboard floor and glowing objects.

![image](https://user-images.githubusercontent.com/32600939/122676825-ab64f600-d1ad-11eb-9c0c-c3beeda2be66.png)

Meta hood doesn't really have a place anywhere I can see.

![image](https://user-images.githubusercontent.com/32600939/122676615-cbe08080-d1ac-11eb-813c-a27fdafa2606.png)

These goggles need a retexture to not be cracked/dirty.

![image](https://user-images.githubusercontent.com/32600939/122676199-fb8e8900-d1aa-11eb-8c4f-048703da8edf.png)

This rifle is not really usable due to the wackiness/post apocalyptic theme.

![image](https://user-images.githubusercontent.com/32600939/122675931-b9b11300-d1a9-11eb-9447-79da8493254a.png)

This sword doesn't make sense in the context of character weapons so it doesn't really have a place.

The current plan was to use the megasword and bow -- I haven't seen any other weapons that will make it in.

![image](https://user-images.githubusercontent.com/32600939/122675225-799c6100-d1a6-11eb-9973-9ae888cd2116.png)

Re: the above the pistol needs a redo to add uniqueness, otherwise it probably doesn't have a place as a character weapon (I'm not sure a pistol even makes sense as one of these).

![image](https://user-images.githubusercontent.com/32600939/122673481-a3ea2080-d19e-11eb-9dd1-0e6545c5d91d.png)

Likewise, the scythe is a good weapon concept in theory but the post-apocalyptic wacky theming won't work as a character weapon.

![blender_a7ZuJzJjm4](https://user-images.githubusercontent.com/32600939/122673074-d3982900-d19c-11eb-9e37-dedd050a29fc.png)

Unlike the reference, this one is too smooth/pristine of a look to be usable. There are some good ideas here but overall I can't find a place for it without major changes.

![image](https://user-images.githubusercontent.com/32600939/122672519-dba29980-d199-11eb-89cf-86aa9e4958a7.png)

This is a decent foundation to start with for a backpack. I'd have to think about this more but if it had one more unique feature I can fit it in.

![image](https://user-images.githubusercontent.com/32600939/122672801-6a63e600-d19b-11eb-8326-e47eed01580f.png)

This backpack has way too much going on, and is leaning into the post-apocalyptic thing too far. I would go back to the drawing board with the backpack base.

![image](https://user-images.githubusercontent.com/32600939/122829267-cb331180-d2b4-11eb-9d40-fd1e7f942f5e.png)

The bot so far seems good.

![image](https://user-images.githubusercontent.com/32600939/122663932-0f66ca80-d16c-11eb-9baa-48a4ff09aeb6.png)

The pets are all good, but I would make sure to not reduce any texture sizes (we can use jpeg/ktx2 though).

![image](https://user-images.githubusercontent.com/32600939/122658389-8f743c80-d13a-11eb-9016-887448377113.png)
![image](https://user-images.githubusercontent.com/32600939/122661450-7084a300-d158-11eb-8f57-09107afab5e3.png)
![scifi-club](https://user-images.githubusercontent.com/32600939/122662084-58b01d80-d15e-11eb-917f-141468e1e61e.png)

**Comment by avaer** [comment]
@madjin is all of this being tested in THREE.js? In general custom shaders in Blender tend not to work out, so the shader editing work worries me.

**Comment by avaer** [comment]
Also, we are keeping the originals so that we can redo bad optimizations from the base art?

**Comment by avaer** [comment]
https://github.com/webaverse/app/issues/1316#issuecomment-865148719

I mostly agree with Via here, there is no need to optimize until the assets are done (and few of these are).

Things like decimation, shader editing, and texture resolution reduction should be done with care and context. For example, some of these should be very high quality since they are one-time loads and central set pieces where we can pay the load cost.

What is more important is probably reducing draw calls (materials) but even then I would make sure you've profiled this in-engine rather than optimized by file size.

**Comment by madjin** [comment]
All of these have been tested in https://gltf-viewer.donmccurdy.com/

**Comment by Vianvolaeus** [comment]
https://github.com/webaverse/app/issues/1316#issuecomment-866529204
> Also, we are keeping the originals so that we can redo optimizations from the base art?

Any textures my end are still available in their respective SP projects and can be revisited at any time.

I would like to think that the decimated assets are being exported as a modifier rather than directly applying them - we can do this in Blender, it's entirely non-destructive. Just add the Decimate to the Modifier stack and *do not apply it* - just export it with it there at it's correct settings. You can preview a wireframe using Overlays.

If a single individual is going to handle texture optimization and size reduction, they should have some understanding of Texel Density and the 'rules' / exceptions for environmental assets, 'hero assets', etc. 

These are considerations that should be made in the initial process for creating objects / scenes, but will still come into play when doing optimization after completion.

For example: the Megasword can have a 2K texture set, whereas common / NPC weapons may have 1k/512 etc depending on their importance, distance to camera, things like that. I'm trying to find an easy to digest overview of the concept.

**Comment by Vianvolaeus** [comment]
https://github.com/webaverse/app/issues/1316#issuecomment-866526616

> These goggles need a retexture to not be cracked/dirty. 

Done today:
![image](https://user-images.githubusercontent.com/80061436/123112772-e9744b00-d435-11eb-8efd-52a97ecd3abd.png)


> This is a decent foundation to start with for a backpack. I'd have to think about this more but if it had one more unique feature I can fit it in.

Both of these assets were designed for Citrine specifically and not as a general asset - not sure if that was communicated properly / if that is influential in any changes.

The current version has the wrench prop in the pocket, but I think there's still some room to make it a bit more interesting. Adding tools or other 'engineer' props seems like it'd add too much clutter.

I was cautious to add too much with the backpack in that regard, as most customization to an item like that usually denotes some kind of personality or interest of the owner - patches, pins, etc - and I didn't want to give it a bunch of wear and tear. 
If there's something that fits the character in this regard then I think that'd be a good direction for it.

**Comment by madjin** [comment]
> Also, we are keeping the originals so that we can redo optimizations from the base art?

None of the originals have been replaced, I just upload new files (.blend or .glb) in addition to what's already there.

**Comment by Vianvolaeus** [comment]
This is something that will be ongoing throughout any artistic process, particularly on the 3D side.

We may want to define some solid polygon budgets, texture budgets, etc to work within so there's less manual asset checking, and more of something artists can fit into their pipeline and have a target to hit.

**Comment by madjin** [comment]
18. Garden Kit

Before: 138 MB
After: 17.3 MB

Textures came in as 4k, resized and compressed to 2k each. Triangle count is already good (43.5k)

![image](https://user-images.githubusercontent.com/32600939/127666125-6c75258b-c8b7-4bd6-b31c-2000a6a3873d.png)

![image](https://user-images.githubusercontent.com/32600939/127666658-517fb880-0cb0-4018-ac42-44e2b32b4fb4.png)
