### ISSUE TITLE
Art: Common assets for remixing

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1322]
All of the current assets that we have are very unique and stylized. For creators, we need an open source example repo of each NFT type that is low poly, CC0, UV maps to easily remix.

1. Pets (walking / flying)
1. Swords
1. Wearables
1. Guns
1. Pickaxe
1. Avatars
1. Architecture
1. Bow

**Comment by madjin** [comment]
1. I'm fine with blobs / dragon being CC0 walking pets
2. I downloaded CC0 swords, will make a repo
3. We could have a hat and backpack for this
4. Need a simple gun / rifle that can be reskinned
5. Need a simple pickaxe that can be remixed
6. Cryptoavatars (Orion)? VRoid defaults?
7. I've got some houses, and the home-space shipping container
8. Need a simple bow that can be remixed

**Comment by Vianvolaeus** [comment]
This was discussed as a usecase for some of the modular content that was made in the past, eg: hoverboards, pistols that Sunny made. They're designed to have a multitude of styles applied to them from a material standpoint, while retaining a specific style with some limited customization.

**Comment by Vianvolaeus** [comment]
> Cryptoavatars (Orion)? VRoid defaults?

Avatars will need to follow a structure that's compatible with the engine at present. VRoid's aren't a bad idea, but we might want to encourage usage of the optimization tools that are available in Studio - since they're about 15 materials each with their own textures by default.

I was thinking about some kind of 256fes base model that fits the same bone hierarchy etc could be fun as well - easy to translate a style and texture them in pretty much any program, due to their limitation in texture size / materials.

If by CryptoAvatars you mean the project rather than the concept, we should probably reach out to them directly, I imagine they'd be onboard with working directly with whatever plans we have - they're eager for more distribution and users of their own platform, which could be beneficial for us.

**Comment by Vianvolaeus** [comment]
This may want to be backburnered until the key character assets, weapons, and other lore relevant items are finished. Distributables aren't necessarily as important as the world building elements we need right now, and an open content drop would likely generate a lot of interest in the platform if we push it correctly - so we should have a world and platform ready for the people that would be using them.

Remove the label if in disagreement, just organising.
