### ISSUE TITLE
Substance Painter: update + localize files next to assets

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1340]
Right now the substance painter files are scattered around the assets they apply to.

Also the substance painter files are out of date?

![image](https://user-images.githubusercontent.com/6926057/124577739-89a97700-de1b-11eb-8646-603b465b2a1d.png)

**Comment by Vianvolaeus** [comment]
Given the large file size of these, it might be advantageous to wait on #1337.

As for the SP versioning, that'd be since they were made in 2020 - 2021 has been somewhat unstable since launch, notably recently the removal of entire asset libraries from the program, performance instabilities, etc. 
If necessary, I can move to 2021 (and will do in future anyway), but since this most recent edition has been *so* disruptive I've held off for a bit on it.

I was assured by Adobe / SP staff that compatibility (going forward) shouldn't be an issue.
