### ISSUE TITLE
Assets: delete all model "drivers"

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1341]
What were the drivers supposed to be doing for assets (particularly the sword)?

Currently it interferes with proper morphing. Unless there's something I'm not seeing, ideally all drivers are deleted in all assets.

**Comment by Vianvolaeus** [comment]
They're there for creating animations, as they can control multiple morphs at the same time. It's a simple, faster way of controlling multiple shapekeys at the same time. 
I added one for the sword since it's made of multiple parts (the trigger was added after the asset was finished, no design phase etc) - can be removed if it needs to be.

**Comment by avaer** [comment]
I see, that's an interesting idea, but for coding things it's easiest to keep all of the keys separate rather than doing any sort of driving/merge.

**Comment by avaer** [comment]
I think this might be interfering on the face capture rig...
