### ISSUE TITLE
Art: Schools

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1348]
Schools enforce aesthetics of the Zones using Zoning laws. Some zones are very strict and some are lawless. Here are some ideas regarding the architecture and design of classrooms.

![image](https://user-images.githubusercontent.com/32600939/124816562-a5ee0680-df36-11eb-8cd3-58d60985ae17.png)

![image](https://user-images.githubusercontent.com/32600939/124816577-aab2ba80-df36-11eb-8189-e05ecf41f821.png)

**Comment by madjin** [comment]
1. The exterior / facade looks very much like the citadel, could these be related? The citadel world is inspired by a "home world" in a video game, seems fitting if so. The interior could perhaps even be classrooms. https://github.com/webaverse/app/issues/1145

Perhaps can renovate the interior of each wing into classrooms?

![Citadel_CM_2 1](https://user-images.githubusercontent.com/32600939/124819025-b8b60a80-df39-11eb-9c47-5d6b8332e82d.jpg)

![image](https://user-images.githubusercontent.com/32600939/124818938-9ae8a580-df39-11eb-8846-3c677f0c9b4d.png)

2. Reminds me of Gunter's Universe! Texta had once something modeled something a similar way before.

![image](https://user-images.githubusercontent.com/32600939/124818779-712f7e80-df39-11eb-896e-39f80feed07e.png)

3. This reminds me of the Internet Archive so much. It would be super cool if we could use the same base model for this, remodel / retexture.

Github: https://github.com/madjin/internet-archive-vr

The IA can be tied into the story somehow since it aims to live up to being the Library of Alexandria 2.0. Also, a digital library archiving and providing universal access all of humanity's knowledge is a great basis for a university. Perhaps the physical building along with the world, has since disappeared so all that is left is the 3D scan artifacts.

![internetarchive](https://user-images.githubusercontent.com/32600939/124819403-367a1600-df3a-11eb-8732-8fdbf2856cfa.png)

**Comment by madjin** [comment]
Another idea for classroom designs is inspired by Hogwarts. I think the small size classrooms and high ceilings are a really great example of something optimized for spatial learning which is the future when screens become deprecated.

![image](https://user-images.githubusercontent.com/32600939/124816828-f9605480-df36-11eb-9f72-a998f6a75714.png)

![image](https://user-images.githubusercontent.com/32600939/124816989-30366a80-df37-11eb-9b1d-c4f16406f06e.png)

![classrooms](https://user-images.githubusercontent.com/32600939/124817400-c1a5dc80-df37-11eb-82c3-3d1f000c1268.png)

Lastly, I've got a number of ghost hackerspaces (they have all since moved from these scanned locations) that we could use. I've seen what 3D modelers can do with a matterport scan reference, turning them into something as quality as a AAA game. Perhaps these ghost hackerspaces are tied into the lore as some assets that were restored long ago from the archives?

- https://hackmd.io/@XR/hackerspaces
- https://github.com/madjin/noisebridge-vr
- https://github.com/madjin/nsl-vr
- https://github.com/madjin/omnicommons-vr
- https://github.com/madjin/hacklab-vr

**Comment by avaer** [comment]
Exactly: the citadel became a school at some point. It also took on official government and military/rules enforcement roles.

The model we have a is a good start, but we’d want it to connect to the street (ie have a natural place at y=0 where the street passes through), and perhaps even expand the building even more to fit more kinds of rooms inside: offices, government chambers, military loadouts/training grounds/test ranges.

Since it is a tall building, floors and elevators to higher up rooms is a natural idea. Perhaps the model should even be split so we can separately load different chunks/lods as we get close to different features (already the interiors we have are separate).

Making the school even taller and larger is good; it is supposed to be a massive landmark of the starting area.  

I like the Harry Potter idea for classrooms and it makes sense as a spatial evolution of learning, with multiple classrooms in the main building (though they could actually be different copies of the same model).

We can have meetings inside the school, and access can be gated, If the keycard unlocks something then the natural idea is that it lets you access the school, where most cool things are. If we have offices and chambers in the school they can be separately owned and decorated by members, but that should be self contained (perhaps on the higher floors).

Inside the school is a good place for testing npcs too.

**Comment by madjin** [comment]
> Ignore the texture changes, I'm testing different textures and kitbashing examples.

There's currently 2 wings of the interior citadel. First thoughts is we need to remove all the stuff inside to make room for desks, screens, etc. Then, the arches should be turned into stained glass or windows to allow light to enter the classroom.

![image](https://user-images.githubusercontent.com/32600939/124998548-9f38bf80-e01a-11eb-92a2-7036e5ed122b.png)

Next, the ceilings are too low in these rooms and should be heightened.

![image](https://user-images.githubusercontent.com/32600939/124998460-76182f00-e01a-11eb-9354-7f6ef6999d70.png)

Also, perhaps we should have some sort of elevator in the building as a way to move up / down? This is how it looks from the outside.

![image](https://user-images.githubusercontent.com/32600939/124998969-4a497900-e01b-11eb-95a7-3e585979a8df.png)

There can be some kind of elevator system in the main hallway (hid the center sculpture for a clear shot)

![image](https://user-images.githubusercontent.com/32600939/124999056-6ea55580-e01b-11eb-8210-c675b94f9f1b.png)

**Comment by avaer** [comment]
It would be easier to visualize this if the textures were removed (they need to be redone anyway).

**Comment by avaer** [comment]
There can be multiple elevators and you can see outside when you are rising.

![5A487C62-1F6E-477B-B9B0-A1D0A4FBFA8F](https://user-images.githubusercontent.com/6926057/125006325-dcf21400-e02b-11eb-9fc4-c5c0674435d3.png)
![2175B04F-EED0-4A84-B9A1-40CA1B32B097](https://user-images.githubusercontent.com/6926057/125006327-dd8aaa80-e02b-11eb-9134-81b69ecc0f9a.png)

Now that I think about it the entire shinra building is a good inspiration in its structure and enormity (though not really in style).

**Comment by avaer** [comment]
Going off of Final Fantasy, FF8 also has classrooms that I think fit in terms of geometric structure (though not necessarily textures).

![shinra](https://user-images.githubusercontent.com/6926057/125006696-b97b9900-e02c-11eb-9e60-53cfad1fe8a1.jpg)

**Comment by avaer** [comment]
Actually if I were to choose a property with the closest design it might be FF8 gardens now -- https://finalfantasy.fandom.com/wiki/Garden. The themes changed quite a bit since we started on the citadel design journey.

![garden2](https://user-images.githubusercontent.com/6926057/125006920-39a1fe80-e02d-11eb-9f5c-13474164e455.png)
![garden](https://user-images.githubusercontent.com/6926057/125006919-39096800-e02d-11eb-8d2d-0a236af865f7.png)
![garden3](https://user-images.githubusercontent.com/6926057/125006921-39a1fe80-e02d-11eb-9592-4eb72c9af28c.png)
![garden4](https://user-images.githubusercontent.com/6926057/125006991-5d654480-e02d-11eb-833b-5390e33fb504.png)
![garden5](https://user-images.githubusercontent.com/6926057/125007122-97364b00-e02d-11eb-8111-0a0ef7ebc12e.png)

Though I think FF8 goes too crazy, the aesthetic is close and cohesive, and evokes the same things that popped up in the lore -- namely the merging of an education and government institution.

**Comment by avaer** [comment]
If this is too far from what we have I think it's fine to start from scratch now that requirements are more clear.

**Comment by avaer** [comment]
Jin had a good idea of building this gradually; putting up a door on unfinished areas, with a link for people to design and contribute rooms for e.g. SILK.

**Comment by plankatron** [comment]
> Jin had a good idea of building this gradually; putting up a door on unfinished areas, with a link for people to design and contribute rooms for e.g. SILK or an actual title deed to the space (the interiors of the citadel make sense as user editable rooms to me).

**Comment by plankatron** [comment]
We could have a few door variants for different types as well
