### ISSUE TITLE
Safari and Firefox not supported

### ISSUE THREAD

**Issue by golergka** [webaverse/app#1356]
## Steps to reproduce:
1. Launch the app
1. Open the localhost address on Safari or Firefox

## Expected result:
I see the app

## Actual result:
Safari:

> [Error] TypeError: Module specifier, 'three' does not start with "/", "./", or "../". Referenced from http://localhost:3000/app.js
	promiseReactionJob

Firefox:

> Uncaught TypeError: Error resolving module specifier “three”. Relative module specifiers must start with “./”, “../” or “/”.

# Discussion:
App uses importmaps for it's modules, but they [are not yet supported in Safari, Firefox, and other browsers](https://caniuse.com/import-maps). May be some other, more portable solution can be used?

**Comment by avaer** [comment]
This is indeed due to import maps. We were using many many other solutions in the past: local script rewriting, service worker intercept, proxy rewriting, asking the user to write against our endpoint.

But they are all worse, slower, and buggier than the import map solution.

It could be investigated more but not supporting import map less browsers was a deliberate choice for now.
