### ISSUE TITLE
Art: Great Filter Wall

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1358]
Between each Zone on The Street is a Great Filter, unique geological features that are difficult to cross for some reason. Each filter is different and unpredictable. The world is infinite on all sides but eventually you will reach a void.

For the first Great Filter we are thinking about a giant wall that seems to extend infinitely in either direction with a small gap that exposes an entrance into the forest (https://github.com/webaverse/app/issues/1313). Good example can be seen from Maze Runner:

![image](https://user-images.githubusercontent.com/32600939/125155089-9be12900-e12b-11eb-9514-3b9c9fba00e2.png)

This may need some concept art first from front / top down view.

**Comment by avaer** [comment]
There would be a gate in the middle that can open and close. The model is best separate from other models. The wall doesn't need to be infinite, we could do with just having repeatable chunks that we can instance.

**Comment by avaer** [comment]
This wall is a pretty good reference for a filter entrance, it is looming and brutalist.

**Comment by avaer** [comment]
The height of the wall is also a good guide for how tall the forest should be.

**Comment by madjin** [comment]
trying out different textures from https://texturehaven.com/textures/?c=rock using https://github.com/eliemichel/LilySurfaceScraper

![image](https://user-images.githubusercontent.com/32600939/125179891-4b1c0f80-e1c1-11eb-81ba-6d46555b37ba.png)

**Comment by avaer** [comment]
I think the brutalist concrete tilings add a lot of flavor.

![image](https://user-images.githubusercontent.com/6926057/125179937-ddbcae80-e1c1-11eb-8189-bbc7899a2475.png)

**Comment by madjin** [comment]
Regarding the entrance, I think a giant door receding into the ground slowly would be more interesting than sliding in the sides. There is a longer anticipation period before the player gets to see what lies beyond the entrance.

**Comment by GaladWarder** [comment]
Here's what I came up with - since the Filter itself is the forest, and the wall is just a wall, I focused mostly on the feeling and mood of the Filter itself.

There are a few wall options that feel more interesting than just a plain rectangle, and a color and mood key illustration on the sheet.

![GreatFilter_ConceptSheet_V1](https://user-images.githubusercontent.com/29031531/125954216-58596c73-d20c-417c-bea6-c54d8ead2081.jpg)

**Comment by avaer** [comment]
This looks really cool as a concept and it's catching the nuances of the vibe.

However that wall looks very geometry dense in places, so if we want the wall to be long it might eat a lot of tris.

![image](https://user-images.githubusercontent.com/6926057/126001777-d0b10c7c-1cdf-489b-8f76-9c2e49377e52.png)

I'm more a fan of just the contrate blocks which can be textured in 4K.

![image](https://user-images.githubusercontent.com/6926057/126001817-2bb7bfc2-f14a-4e61-8048-3a4c19a6cc25.png)

Scillia is running on top of this wall in the trailer, so having an interesting top is a good idea. I don't think we need to focus on any sort of lettering on the wall like making a W or a U, but ramps and details up there is good.

![image](https://user-images.githubusercontent.com/6926057/126001723-8127bb4b-6a7d-4d7f-a60c-e30f64d94bd7.png)

This is also a good reason to keep the side/guard path, since it is another lane to run on, but I also worry this might eat many tris if there's a complex railing.

![image](https://user-images.githubusercontent.com/6926057/126002151-9dca652d-0cbc-42f1-a368-be18f26eca49.png)

**Comment by madjin** [comment]
Friend is taking a stab at this for some SILK

![image](https://user-images.githubusercontent.com/32600939/126016174-6628c29e-6c41-414e-b998-84ca1f618cb9.png)

![image](https://user-images.githubusercontent.com/32600939/126017390-75b171c4-08bb-4d9b-931a-eed55b79a346.png)

Could have some kinda lights here?

![image](https://user-images.githubusercontent.com/32600939/126017539-c0368e19-9275-49e8-bdf2-2673c7f38df4.png)

Can run these textures through substance painter smart materials to give it more of an aged look or use a trim sheet.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/126020512-e4c3ddc5-7df1-4320-b8fa-cb01ea7bf4fa.png)

http://hunterfox.info/GiantWall.blend

**Comment by madjin** [comment]
Tons of good textures here: https://ambientcg.com/list?category=&date=&createdUsing=&basedOn=&q=+concrete+&method=&type=&sort=Popular

Can try things out faster using this plugin: https://github.com/eliemichel/LilySurfaceScraper
Instead of downloading, can import to blender with URL of texture in your clipboard

Quick example: https://ambientcg.com/view?id=Concrete026
![image](https://user-images.githubusercontent.com/32600939/126020687-956045ed-18a0-4c83-84c8-3a73b5fb635f.png)

For creating ivy: https://docs.blender.org/manual/en/latest/addons/add_curve/ivy_gen.html

**Comment by avaer** [comment]
I still think grants concept is pretty good.

The block texture here makes sense and the lights are a cool idea. However the screws don’t make sense and the ivy is very tiled. If we are going to do any sort of lights it should have some symbolic meaning like words made of the symbols.

![BCB0902A-78E3-4352-857E-8AD8A3FBDC34](https://user-images.githubusercontent.com/6926057/126025897-90308ad0-96be-41ea-b5b1-d3adfc7ad4b7.jpeg)
![92C5B1AB-542D-425C-B8F3-5E1D305A493C](https://user-images.githubusercontent.com/6926057/126025898-c195624b-8369-4f88-9b88-1f5f939a5117.jpeg)

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/143451408-e3df7acb-000a-47d8-9285-231231e0f3da.png)
Updated Great Wall

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/143576553-1beb4316-5ff0-4700-b097-bf1dfc8330ce.png)
Updated Textures of the greatwall pertoday
