### ISSUE TITLE
Art: WFC/Wave function collapse city

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1365]
https://github.com/marian42/wavefunctioncollapse

This is a good Unity repo + codebase for procedurally generating cities, better than what I had planned. It essentially uses a set of prefabs to glue together a cityscape based on fills and heuristics.

![img](https://marian42.de/article/wfc/blocks.png)

The actual blocks FBX is here: https://github.com/marian42/wavefunctioncollapse/blob/master/Assets/blocks.fbx

![image](https://user-images.githubusercontent.com/6926057/125164691-7d962000-e161-11eb-99c8-8e64203b56fc.png)

We can use this to fill the need to have a city in Zone 0, meeting the last requirement for the trailer.

The work involved is:

* [ ] create a more solarpunk set of prefab blocks, by editing the existing `blocks.fbx`; we might also want to create the textures at this stage
* [ ] update the algorithm to increase height a bit
* [ ] generate a bake
* [ ] fix textures (if needed) and and edges to create the final city model

#### Inspiration
![solarpunk](https://user-images.githubusercontent.com/6926057/125165003-02ce0480-e163-11eb-8ce2-86a4cc12812c.png)

**Comment by madjin** [comment]
Familiarizing myself with this project, so far set it up and usied https://github.com/Plattar/gltf-exporter to export as GLTF

![image](https://user-images.githubusercontent.com/32600939/126025589-f2aedfe0-eb59-4ffc-bc9d-75e0583f50dd.png)

124k triangles from a 16x16 area generation
![image](https://user-images.githubusercontent.com/32600939/126025604-5e5ada51-68db-4633-b764-5996833f288a.png)

**Comment by madjin** [comment]
More pics:
![image](https://user-images.githubusercontent.com/32600939/126025904-4299eba8-d104-4cd3-aa75-24d3b200c5ce.png)
![blender_KBgRPpnvWC](https://user-images.githubusercontent.com/32600939/126025909-a08f1a60-4e89-4fa7-b527-39fd4d754573.png)
![blender_WXXFjZ8OhB](https://user-images.githubusercontent.com/32600939/126025913-658dfcdb-4352-40be-bf4e-5d4302a0bca9.png)

Could also generate these more vertically as well
![image](https://user-images.githubusercontent.com/32600939/126025961-5e0b5619-2079-489e-bb5d-5a2f3da03d2e.png)

**Comment by avaer** [comment]
Great research, looks sick. 😍  I’m curious how this textures. If you uv/texture the source does it cool me out in the model?

Once we understand the process, we should redo the ingredients and textures to be strong “Webacity”/“Zone 0”/“Nihon” architecture.

It would take a bit of work, but the resulting effect might be pretty magical.

**Comment by madjin** [comment]
I did a bit of testing to see what the optimal workflow. When I first attempted to modify the pieces inside Unity, lets just say it didn't like that and I had to nuke / redownload the entire project.

## Meshes
The blocks.fbx file is hard to edit in Unity and blender because when you open it up it looks like this:
![image](https://user-images.githubusercontent.com/32600939/126042646-07756f3a-470b-4a96-835e-b5efb1cd00e5.png)

Gotta open up the prototypes file where all the pieces are individually arranged
![Unity_MkOe8UtKd3](https://user-images.githubusercontent.com/32600939/126042656-b002c02e-1ad7-4d20-a72f-cb051102edef.png)

You can then change values in the `ModulePrototype` component where you can see a preview of what it looks like in the context of other pieces. Great way to pre-visualize the generation. I don't recommend changing the materials at this step.
![image](https://user-images.githubusercontent.com/32600939/126042635-b25628ec-e691-450a-b04a-1e87ec824b54.png)

It took me a bit to figure out how to modify the meshes, both blender and unity have different scale / coordinate systems.

First, figure out what piece you want to edit based on step above so you know how it'll fit with other pieces. Then, import the FBX file into blender with  **Apply Transform** box checked.

![blender_kUyXCdi5ak](https://user-images.githubusercontent.com/32600939/126044336-e179c20d-a3de-47b8-9529-ce01746c0ab0.png)

Search for the piece you want to edit, then hide everything else to make it easier to work on just that. Make sure whatever you're doing is joined to that specific piece.

![image](https://user-images.githubusercontent.com/32600939/126044618-4fa876a4-2d42-438a-b916-806f42f95880.png)

When done, unhide everything again and export with **Apply Transform** box enabled again. You can name the fbx file whatever you'd like.

**Import custom FBX**

When you import the FBX into Unity make sure to uncheck **Convert Units** and check **Read/Write enabled**.

![Unity_6bziidNSNX](https://user-images.githubusercontent.com/32600939/126044523-55384475-d8e1-4638-8433-32bd54aaef89.png)

Open up the Prototypes.unity project and drag the Prototypes.prefab into the Hierarchy. Select the piece(s) that you modified and replace the Mesh Filter with your new piece from the FBX you imported (mine was blocks7.fbx).

![image](https://user-images.githubusercontent.com/32600939/126044690-00e355b8-e9f6-483a-b96c-2a20510de8c0.png)

Save the project. You can now open the Game.unity project and generate with the modified pieces.

![Unity_77YUXILdWE](https://user-images.githubusercontent.com/32600939/126044709-3f38aae7-7618-4858-900c-0700dda48cef.png)

## Texturing

I'm still figuring out the workflow for texturing modular pieces before generation, something seems to break which causes them to disappear in the output. In the meantime after generating you can either texture in Unity or Blender no problem.

Changing the material for a piece in Blender will change all of them.
![blender_B3fzPik05V](https://user-images.githubusercontent.com/32600939/126045073-c53a073c-28ec-4474-bfc2-746442690347.png)

**Comment by madjin** [comment]
Figured out texturing pre-generation, was simpler than I thought. Open the prototypes prefab then search for the piece you want to retexture. If that piece is missing from the Mesh Filter search for it again and respawn it. Then drag the material onto the piece and go back to the scene.

![image](https://user-images.githubusercontent.com/32600939/126045497-fa3e1890-12f7-4094-a026-c4626004fc5f.png)

Next open ModuleData and click Create module data.

![image](https://user-images.githubusercontent.com/32600939/126045535-e1109c24-6e13-4ffa-a67e-1b2afe0c04a9.png)

Can then re-open the Game.unity project and Initialize the area to generate with the remodeled / retextured pieces. Ta-da!

![image](https://user-images.githubusercontent.com/32600939/126045596-0d1bd553-8bb6-4037-bdde-28bc87f2804a.png)

**Comment by madjin** [comment]
Author of the repo is working on a rewrite as a full blown city generator https://twitter.com/marian42
![image](https://user-images.githubusercontent.com/32600939/126046584-9121cfa9-72a2-4432-a216-ecdc1015835a.png)

How it looks with textures: https://pbs.twimg.com/media/E6B-OpGWYAIQeUJ?format=jpg&name=4096x4096
![image](https://user-images.githubusercontent.com/32600939/126046596-7e994183-4d72-4abe-964a-31abc16a7a2a.png)

Hasn't decided if it'll be hosted on GH again, wonder if we could collab

**Comment by avaer** [comment]
Sounds like we should proceed with generating Webaversey blocks then, but I think first it will need a lot more ingredients from Pinterest.

**Comment by madjin** [comment]
## Notes on workflow

1. First we're starting with the base mesh layer. We could add simple textures at this step. There's 454 modules.
2. Next we can do a detail pass with an asset kit ready for adding plants / decorations. Doing this collaboratively or as a timelapse would make great fodder for social media.

When redesigning modular pieces, we'll want to edit the blocks.fbx file in the way I described at the top of the comment above:
> Search for the piece you want to edit, then hide everything else to make it easier to work on just that. Make sure whatever you're doing is joined to that specific piece.

In order to check how a piece looks like next to another piece we can view previews in the Prototypes.unity file or generate everything and check. We'll want a quick feedback cycle. I think it might be fine to keep the UVs really simple, could retexture in post plus it could open up room for graffiti in the future.

### Window Tills

Name: **High_Wall_Window**
Add window till for plants to overhang (don't add plants yet)

![image](https://user-images.githubusercontent.com/32600939/126069915-5c4d5173-cf3b-496d-9cfc-8e8c654a0540.png)

Now in the blend file you could search High Wall Window and find all the windows that need plants in the tills.

![image](https://user-images.githubusercontent.com/32600939/126069876-bec4c721-b1a6-4bd9-88d4-14f0e2298a63.png)

### Example: Roofs

Name: Search "roof"
Replace some with steel/glass to test

One of the common threads of solarpunk aesthetic is light coming in from high windows / glass ceilings. There is access to the rooftops, but the rooftops do not serve the interior sections well to allow for light.

![Unity_wpey7A5s5R](https://user-images.githubusercontent.com/32600939/126070619-7c795221-b39b-4511-b983-5ef36913a242.png)

One of the challenges with this is that there are a lot of individual roof pieces. Something we could do is perhaps instead of shingles, we replace some roofs with steel and glass and test.

![image](https://user-images.githubusercontent.com/32600939/126070730-87587d16-61c2-4451-ae27-0751a3a54902.png)

### Asset Kits:

After the initial base is generated we can go back in and add details

- doors
- lights
- plants
- signs
- booths
- vending machines
- fans (adds movement)

Plants

![image](https://user-images.githubusercontent.com/32600939/126071373-f0b5c476-92d8-4596-8543-be070570ce11.png)

Signs and hanging decorations

![image](https://user-images.githubusercontent.com/32600939/126071548-f16c78db-b7bf-4c48-8b9a-18183f92f142.png)


### Idea: Facade

The output leaves a lot exposed, so we'll need to think of how we want to patch that up.

One way is to add scaffolding on the outside and make it look like a work in progress. This would be an honest expression of how the world is a constant work in progress, similar to booming cities around the world. It's also kind of cool in the way that it's like the grid being applied vertically.

![image](https://user-images.githubusercontent.com/32600939/126071120-a15f3348-abd9-46c9-a301-4f6177aab13f.png)

Another idea I had was to enclose it up, perhaps as part of a larger structure such as a mountain hillside. Gerudo Fortress was a cool example of such.
![image](https://user-images.githubusercontent.com/32600939/126071195-bcb3f502-2a83-4fa1-9640-80444169a577.png)

This would add a ton of cohesion since it'd be 1 model gluing everything together, make such optimized through by being enclosed, and be made pretty quickly since the procgen is very geometric.

**Comment by marian42** [comment]
Hello, I hope you don't mind me commenting here!

Some thoughts on the current blocks:
- I've started to put them in multiple files, that makes them easier to edit and it works better with version control. I use one file for roof blocks, one for interior blocks, etc
- The scale is a bit off, the blocks are 2 meters in size, but I think it would work better if they were scaled to 4 meters. Just keep in mind that you might need to scale them up at some point if you want to put regular sized humans into the map. And I think the railings are too tall relatively, so they might need to be scaled down.
- You can add your own blocks and set up data for them, this requires no code. It's totally feasible to add a new type of roof that lets light shine into interiors. Just keep in mind that there isn't necesarily an interior block behind every wall/roof, so I'd make variants of that new roof that can and cannot let light through. And of course you need a matching interior block that connects to the new roof.

Really looking forward to seeing progress on this, I love that you chose Solarpunk as the theme!

**Comment by avaer** [comment]
Some textures/shapes/colors ideas. This is Collision Chaos Good Future from Sonic CD.

![solarpunk6](https://user-images.githubusercontent.com/6926057/126148608-c7f826c3-ef1f-4f70-b456-b0029fad9a7e.png)
![solarpunk2](https://user-images.githubusercontent.com/6926057/126143854-1f57bc65-c858-48d5-af1f-cc5e1b92eabc.png)
![solarpunk4](https://user-images.githubusercontent.com/6926057/126148388-74cd289c-ea2f-40b0-88f0-8d4a824f80c7.png)
![solarpunk5](https://user-images.githubusercontent.com/6926057/126148385-daed77c0-09e6-4807-8a36-ff8d6b159eae.png)

**Comment by avaer** [comment]
An article that made the HN rounds: https://www.messynessychic.com/2021/06/10/inside-the-imaginarium-of-a-solarpunk-architect/

**Comment by madjin** [comment]
- Generate ideas
- Galad can do overpass art

**Comment by madjin** [comment]
Note: We have to replace each block individually in the unity project so its a good idea to take note of which pieces have been modified in the process.

**Comment by madjin** [comment]
Okay we figured out a better workflow, we transfer the modified .blend file of the blocks.fbx file and then export (with Apply Transform enabled) to overwrite the blocks.fbx file in the Unity project Assets folder. As a test @plankatron removed the columns from the wall and shingles on the roof and it worked during initialization.

![image](https://user-images.githubusercontent.com/32600939/126342768-6d9d24ef-f11f-4165-ae01-355a3e69cce4.png)

![Unity_uwonhuosDg](https://user-images.githubusercontent.com/32600939/126342795-e4998dff-0022-47d6-bce1-f6569e7d70d7.png)

**Comment by avaer** [comment]
The AI keeps coming up with `Nihon City` for this city (in Zone 0). Is that appropriate?

I googled it and it does not seem to exist so it is actually original (though I could be wrong).

I did not have any japan references in the prompt so if it came up with this multiple times it seems like it has a strong idea.

**Comment by avaer** [comment]
Checking in on the explanation of why it came up with that:

(this is AI generated)

Is Nihon City a good name for the name these characters inhabit? Why?

I think it is, and not just because I know the name Nihon means Japan in Japanese. I think it's a good name because it makes clear that the City isn't normal. But it is rooted in the real world. Also, I think it's because the name Nihon is easy to pronounce and remember, which is important when it comes to online video games. And I think the name is easy to say and remember because it's an actual name, not a made up one. The fact that it's a real name gives it a sense of authenticity.

**Comment by madjin** [comment]
## Simplification

We need a more simplified generation in order to make concept art of new designs (geometry / textures) before modifying the pieces.

### Modifications

1. Remove these lights, make these walls more plain.

![Unity_yiPNvr9Px6](https://user-images.githubusercontent.com/32600939/126555822-2c2ab90a-237c-4965-bce3-af7f7170e610.png)

2. Remove the Grandfather clock (perhaps we can consider a new prop instead?)

![Unity_pKJonsC6Oq](https://user-images.githubusercontent.com/32600939/126555922-38bec95e-ab1a-4218-8f1f-3a3d763e59fa.png)

3. Simplify these walls by removing the lights

![Unity_ATElbk4OUC](https://user-images.githubusercontent.com/32600939/126556016-1961649b-19f1-414b-a9e6-9070ad3303f8.png)


![Unity_uwonhuosDg](https://user-images.githubusercontent.com/32600939/126556206-c991f4ba-8c6c-4d18-83c2-ab493ed1edcc.png)


## Updates

@plankatron figured out the minimal starter set for generating maps with: https://github.com/marian42/wavefunctioncollapse/issues/20, has 3 sets that work

**Comment by avaer** [comment]
> @plankatron figured out the minimal starter set for generating maps with: marian42/wavefunctioncollapse#20, has 3 sets that work

But we are not doing that right?

**Comment by plankatron** [comment]
**![17-Buttress-Columns-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585720-7ec946b8-d699-43e5-9726-88ac6e358716.jpg)
![16-To-the-City-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585730-c364b1c4-aa13-4c37-984a-6b8c75b180dc.jpg)
![13-Sleeping-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585743-ee754617-400e-461b-88d6-33808e0321dd.jpg)
![12-Column-Jungle-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585753-712697ba-2000-48b8-867a-b2df02c5912a.jpg)
![11-Inside-the-City-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585772-9ae5bdf2-a908-4b95-884b-b6ff830d30fc.jpg)
![10-Possible-Future-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585812-c1a1652a-bd29-4720-af36-fb87d1a7d9cf.jpg)
![07-Loaded-Interior-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585843-72cdcc2c-3c08-41ca-bb72-345f07b94707.jpg)
** 
![22-Precious-Chaos-Mita-Mitauzo-実-田-く-ら-Intricate-Japanese-Architectural-Drawings-www-designstack-co](https://user-images.githubusercontent.com/5592454/126585700-ddb3b0e8-bc14-43a3-aee4-78b0780bbd5e.jpg)

**Comment by madjin** [comment]
Those are some nice illustrations. I took some screenshots of the latest simplified blend, think we can concept art some good ideas on top of it. Here are some samples:

![Unity_BAlTNpZUf0](https://user-images.githubusercontent.com/32600939/126666030-28c39c95-32c8-47b2-ab33-9361fe40557f.png)

![Unity_XiWDO8e2zO](https://user-images.githubusercontent.com/32600939/126666073-5bc81dba-8b1f-4da6-9b8a-c053ffe8748a.png)

![Unity_BmY4zukmBU](https://user-images.githubusercontent.com/32600939/126666123-3cbeebbf-d956-4ac3-a337-53df156d6cdc.png)

![Unity_J30HuG6CFD](https://user-images.githubusercontent.com/32600939/126666178-04d4722a-8fb6-441f-a451-64075ec86352.png)

![Unity_kikhzOmunh](https://user-images.githubusercontent.com/32600939/126666252-3ecc46e1-39af-4a86-a3ab-47fb032ee6e2.png)

---

**Note: If @plankatron you need front facing pics to make the UV maps faster we can use screenshots like this**

![Unity_bYb7R7YnQ9](https://user-images.githubusercontent.com/32600939/126666350-817f143c-ecec-43c0-ad7a-e87d4b2210b8.png)

**Comment by avaer** [comment]
> https://github.com/webaverse/app/issues/1365#issuecomment-884632571
> interesting shape language :

I agree, very pretty and surreal. Like someone spent lifetimes on this one city. Which would be an appropriate vibe, though hard to accomplish without spending a lifetime. Luckily we have procgen :D

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/127539137-86087581-2925-4e9a-beed-0060bcff1ada.png)
"his is probably the most accurate thing I've seen for how I envision city/Z0 looking like"

**Comment by madjin** [comment]
## Workflow Speed Tip

You can edit the prefab inside Unity and nest objects inside modules then save the module data.

![Unity_An28xfDZYJ](https://user-images.githubusercontent.com/32600939/127576036-3b644742-e72d-44c2-810e-049a5557c721.png)

- open prefab
- drag fbx to module you want
- resize / reposition
- go to ModuleData and 'Create module data'

Then when you initialize the map it should start working in your editor

![Unity_KMpV9XWQHf](https://user-images.githubusercontent.com/32600939/127579109-91849471-604a-4fd5-90a6-f39a86ea4acf.png)

Can export as part of the gltf as well using plattar exporter. Saves a bunch of time!

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/127602126-88dcbf2a-e0c6-4238-98f2-410a9ab94653.png)

**Comment by avaer** [comment]
☝️  Whoa, what's that?

It looks like it's neural.

**Comment by madjin** [comment]
Need to remove these tables

![image](https://user-images.githubusercontent.com/32600939/127669440-c11ac2dd-a24b-477a-a45d-c8d3f6e9e470.png)

**Comment by GaladWarder** [comment]
> ☝️ Whoa, what's that?

> It looks like it's neural.

It's the WIP I put in the Discord from yesterday - used deepdream to transfer the style quickly then I'm overpainting on top

**Comment by Vianvolaeus** [comment]
> ☝️ Whoa, what's that?
It looks like it's neural.

I think I might have a way to achieve similar to this in SP 👀 the edge warping style is something i've messed with a little bit before... If you want me to explore it a bit, I can.  It's generative (non-destructive) filtering.

**Comment by avaer** [comment]
> It's the WIP I put in the Discord from yesterday

Thanks, I see it now.

**Comment by madjin** [comment]
Missed a spot here with the ceiling trim, need to simplify:

![image](https://user-images.githubusercontent.com/32600939/128097531-c5c538fc-26b2-4feb-bc6e-52dbcbc75514.png)

![image](https://user-images.githubusercontent.com/32600939/128097552-875a67e9-15cc-4111-856e-38a9fb4cd813.png)

Here's a preview on how it looks when initializing with nested assets:


https://user-images.githubusercontent.com/32600939/128097783-f86c99e7-e0f8-4cfe-8805-2a04f9e52f64.mp4

**Comment by madjin** [comment]
Comments / Ideas:

This area could be interesting for either hanging lanterns or scrolling LED text
![image](https://user-images.githubusercontent.com/32600939/128098195-5acbf301-3faa-4ec1-97bc-d8e2bfb75f1e.png)

We could make custom fit vines based on the mesh export of the city and edit in post for the columns:
![image](https://user-images.githubusercontent.com/32600939/128098268-4f8dbe1d-dbd2-435f-baca-33cf8989cc39.png)
![image](https://user-images.githubusercontent.com/32600939/128098533-c4366f9e-6d5d-46c7-b865-2ad55b8cfd4a.png)

Trees would look really cool at night with light decorations, would make the zone feel so much more comfy and safe
![image](https://user-images.githubusercontent.com/32600939/128098481-c700ed7e-338d-4a95-9fcb-7a5ae456e556.png)

The trees outdoor need to be changed, they're not that great.

Overall this has interesting and sometimes surprising results that manual work might not provide the satisfaction of. I think there can be a balance between WFC and manual interior design.

**Comment by madjin** [comment]
![Unity_6v7r9t3Hrn](https://user-images.githubusercontent.com/32600939/128257583-e0b828e5-e8e5-4550-ab88-7db5d4c99595.png)

![Unity_IgKcSPnmvh](https://user-images.githubusercontent.com/32600939/128257586-43d7c828-1333-4f90-ac9f-aa6ce03ce97b.png)

![Unity_VFTzKIG0Y5](https://user-images.githubusercontent.com/32600939/128257594-0bf793c7-5964-4e0b-a0cb-c8f4f5c061e4.png)

![image](https://user-images.githubusercontent.com/32600939/128257826-ab4ebd4d-1af4-491e-b82d-298f8d838047.png)

Blender

6x6 area
12 textures
27.2 MB
58k triangles

![image](https://user-images.githubusercontent.com/32600939/128258143-471377e4-3356-467a-968f-3cd5bce077b4.png)

**Comment by madjin** [comment]
Test file: https://cdn.discordapp.com/attachments/641036402829819914/873675931317858344/wfc_12x4.zip

## Textures

I've begun testing out various textures for the pieces in blender by making quick and dirty uvmaps for the pieces and assigning CC0 textures using https://github.com/eliemichel/LilySurfaceScraper. I can rapidly test new textures since applying it to one piece applies to all the other pieces. For somethings like the roof there are 10 pieces.

![image](https://user-images.githubusercontent.com/32600939/128732336-ff8109e0-599c-4f23-8a4b-b7945df647b6.png)

![image](https://user-images.githubusercontent.com/32600939/128734422-080e6ab4-5666-44a4-985e-883c5e0f29e3.png)

![blender_kMu2fiZLWs](https://user-images.githubusercontent.com/32600939/128732594-1045beec-2ac5-47f0-865f-13720ce02216.png)

I'm currently literally throwing stuff at the wall to see what sticks. Here's an unlit look at an example:

![blender_uNBJ8yFqoP](https://user-images.githubusercontent.com/32600939/128733125-685406d7-065a-4995-b2f4-40db0d9c9ff9.png)

The style we want is cartoon / anime. I have ideas on how to post-process the chosen textures to fit the aesthetic.

---

## Geometry

It would look nice to hang art on the walls. We need to smooth out the trim that is on some of these module pieces so we have clear wall space to hang some framed art.

![blender_eItbEb6KOW](https://user-images.githubusercontent.com/32600939/128733349-cd2162d0-0706-4b5d-a7c2-be307204c2b5.png)

## Lights

I could add point lights to some of the module pieces and it will generate the map with all of them there. This is good for the props that have emissive lights, will save a lot of time.

![Unity_Fsk6FR9Oi1](https://user-images.githubusercontent.com/32600939/128734125-e7a45e88-6f1d-436b-aecf-b656e0623406.png)


When exporting to GLTF using plattar plugin and importing to Blender, the lights do appear as nodes but not as lights. Wondering if there's a way to search and replace in Blender?

![blender_9BGpM6mFly](https://user-images.githubusercontent.com/32600939/128734134-1717e43b-b0ed-4e24-8b58-159179843e16.png)

**Comment by madjin** [comment]
Updated latest project files here: https://github.com/madjin/wavefunctioncollapse

**Comment by avaer** [comment]
https://github.com/webaverse/wavefunctioncollapse

**Comment by avaer** [comment]
Closing this because it’s not clear whether we can use the existing work, but the ingredient models are good. We still need to generate this.

**Comment by ahadshams** [comment]
reopening the issue and doing a deep dive 

i found this and found the style quite interesting

https://manifold.garden/
