### ISSUE TITLE
Art: Homes

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1369]
Most people have a house where they control access and decorate in the style of their choosing, from mundane to fantastical elements or even warped realities.

## Inspiration
![homes!UNITO-UNDERSCORE!inspiration](https://user-images.githubusercontent.com/32600939/125174206-a8986800-e191-11eb-9645-00cdd838c156.png)

Perhaps we can go on a VR field trip to check out various styles of homes for inspiration. Here are some worlds I've collected:

Moody by Fins
![VRChat!UNITO-UNDERSCORE!zuMC4tIcSK](https://user-images.githubusercontent.com/32600939/125173789-13946f80-e18f-11eb-92ef-31a3ef132343.jpg)
https://vrchat.com/home/launch?worldId=wrld_acfd9876-5c18-4012-82c0-b00c89afc99d&instanceId=0

Home of The Time by fr1ed
![image](https://user-images.githubusercontent.com/32600939/125173856-7dad1480-e18f-11eb-8188-251f24dc1376.png)
https://vrchat.com/home/launch?worldId=wrld_60f27ea7-a9f0-4aca-aecd-9aba18c86ed9&instanceId=42261

LA Style Mansion by spookyghostboo
![image](https://user-images.githubusercontent.com/32600939/125173916-ed230400-e18f-11eb-91ff-b2c073ed8e30.png)
https://vrchat.com/i/demographic-kickblook-7f8ed
https://booth.pm/en/items/2535448

Home Kit (as seen at Vket) by ecochin
![image](https://user-images.githubusercontent.com/32600939/125174032-7f2b0c80-e190-11eb-8310-5e80502f890b.png)
https://booth.pm/en/items/1570582

![image](https://user-images.githubusercontent.com/32600939/125174060-b26d9b80-e190-11eb-9b3f-419cf615ddbe.png)
https://ecochin.booth.pm/items/1980124

Other things on Booth.pm worth checking

* https://booth.pm/en/items/2906861
* https://booth.pm/en/items/2912266
* https://booth.pm/en/items/2973456
* https://booth.pm/en/items/1509768

I've also got tons of ideas of shipping container homes posted here: https://slate.host/jin/shippingcontainers
![image](https://user-images.githubusercontent.com/32600939/125174234-cfef3500-e191-11eb-8fed-140c1c33002e.png)

It would be very interesting to stack them together.
![jzatxXZdFA](https://user-images.githubusercontent.com/32600939/125174217-b5b55700-e191-11eb-8544-df9fb81e5c8d.png)

Renderdog had a beautiful concept going with [Hito's Free Thought Cafe](https://makersplace.com/jin/hitos-free-thought-cafe-1-of-5-39818/):
![image](https://user-images.githubusercontent.com/32600939/125174267-10e74980-e192-11eb-9a1a-55bfe15c51ab.png)

We can use a different shipping container than the one I've been using for the home space. If we use a standard sized shipping container, it might turn into something practically useful since the interior designs can be adapted to IRL plus they are portable across different zones / virtual worlds.

**Comment by madjin** [comment]
Shipping containers

![image](https://user-images.githubusercontent.com/32600939/125200853-a63e1880-e23a-11eb-87a1-b8854b58804d.png)

- https://www.cgtrader.com/3d-models/industrial/other/low-poly-pbr-shipping-container
- https://www.cgtrader.com/3d-models/industrial/other/48-shipping-containers-set
- https://www.cgtrader.com/3d-models/interior/other/wa-06d34dbd-143c-4388-83a2-634352d56ae4

Japanese Town (comes with individual homes)

![image](https://user-images.githubusercontent.com/32600939/125200863-b0f8ad80-e23a-11eb-9ff6-e2b34a426d42.png)

![image](https://user-images.githubusercontent.com/32600939/125200932-06cd5580-e23b-11eb-92c9-e59b48599b10.png)

- https://booth.pm/en/items/1979962
- https://assetstore.unity.com/packages/3d/environments/urban/shouwa-80-s-japanese-town-model-set-vol-1-house-91384

I like how self contained and fenced the Japanese town assets are. These can serve as design inspiration. Maybe the roofs can be fitted with solar panels?

**Comment by avaer** [comment]
> Maybe the roofs can be fitted with solar panels?

That part doesn’t make sense to me, unless solar energy is simulated.

**Comment by avaer** [comment]
I’m trying to think about the layout here.

It seems like we will have the generated city (https://github.com/webaverse/app/issues/1365) which will take up a lot space and has its own land slots, and therefore possibly home spaces.

There can also be bare home space slots elsewhere, which are empty, which it seems what this issue is talking about.

And then there is home spaces in isolation mode.

Have we thought about how to reconcile all of these to keep it from being confusing?

**Comment by madjin** [comment]
> Have we thought about how to reconcile all of these to keep it from being confusing?

Floating islands perhaps? Simulated Virtual Reality?

**Comment by avaer** [comment]
I devote a week exclusively to thinking about spaces, and I have opinions on what won't work. The main thing that won't work is making these design decisions (especially if it involves art ideas) and backporting them to the implementation (because I tried that).

I think before we start thinking about the homes we're designing or even opening Blender, we need to have a thorough writeup of the gameplay and logic this fits into (Blender can help).

What are these spaces?
Who is using them? For what?
Are there different types of spaces? How do they differ?
Can a space be in two places at once?
Can a space be carried in your pocket?
Is a space always owned or are there spaces with no owner?
Can you walk from a space to a space? What is the layout? Is there a background outside of spaces?
Can two spaces link up like a Game Boy Game Link Cable?
Does a space come blank, or does it come with non-editable stuff, or does it come with editable stuff?

**Comment by avaer** [comment]
Will open an issue for the above.
