### ISSUE TITLE
Art: pose avas with logo

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1380]
Once the avatars are done we'll need a pose set for all of them, hopefully with weapons and logo, that can be used for promo.

I suspect the poses can be made ahead of time, since it's just VRM.

This needs a reference.

**Comment by Vianvolaeus** [comment]
I've been saving character poses used in avatar concepting. There is also a pose library from #1198 I need to review as well.

These *should* transfer across each avatar as required, in Blender.

**Comment by avaer** [comment]
Its not exact, but it’s supposed to come out with this type of vibe.

I imagine mc pointing sword forward, everyone else is in character appropriate shenanigans. Not just posed, but posed in reaction to each other, like it’s a freeze frame of a cartoon.

Of course we would need to come up with this scene, which should be easier when we have the models done.

![1D3F6107-63B7-492A-8AFA-E4D5E271ACF1](https://user-images.githubusercontent.com/6926057/126755360-15790745-fa65-4541-b967-2f96d83d6acf.jpeg)

**Comment by Vianvolaeus** [comment]
Can confirm that poses transfer between characters a-ok in a pose library - was able to (manually, mind) 'merge' pose libraries of mine and @plankatron 's thanks to the armature similarity.

I'd advise anyone doing any ***Armature*** posing with one of the characters to save it to a pose library. I can merge anything you make into a master file so we can do things like the above easier. 

**Facial expressions do not transfer since they are not armature controlled.** Eye position will. 
That said, it's not too hard to manually set them (shapekey pins)

![image](https://user-images.githubusercontent.com/80061436/126805333-6c55efca-6234-44e9-9e2b-6be83976febb.png)
