### ISSUE TITLE
Assets: standard environment

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1393]
The assets all currently seem to be using very different ideas of environment/world setup. There are two main problems I saw:

1) I was not able to find a case where the model in the `.blend` renders out to any of the screenshots.
2) It is inconsistent what the top level object is in these assets. Sometimes it is wrapped with a parent object (it should be), and sometimes it is not (like in the case of Jun avatar).

I think the rule should be if we're doing screenshots to show that an asset is done, then the file should at least have the capability of snapping that screenshot without changing deep blender settings.

Since I am doing composing and engine work now, it is important that assets can be copied and pasted between scenes and they always look this same. This only works if they are designed to render in a specific lighting scheme, and if they can actually be copied/pasted (which collections cannot).

**Comment by avaer** [comment]
I noticed the main problem is the viewport shader settings are all set to arbitrary values during development.

![image](https://user-images.githubusercontent.com/6926057/126934063-93a95c22-dd0b-459a-b2df-90df8358d3fe.png)

**Comment by avaer** [comment]
Due to this I think many of the object materials will need to be redone, since they look bad in standard lighting settings that are consistent across other objects.

**Comment by Vianvolaeus** [comment]
> wrapped with a parent object (it should be)

I'm assuming you mean a collection / folder. If that's the case, that's fine. Works for nested assets, asset variations, etc. 

Models made of different parts should be parented to either their rig (armature object) or an Empty. That will effectively
nest them to a single clickable object. 
Rigged objects are consistent across the copy/paste buffer you are using to compile a scene. I'm not 100% on the Empty solution, (I am fairly certain it works, since sketchfab models converted to gltf etc use this method) but if that doesn't work, we can use a single bone armature and it should work the same. 

> a basic light, everything set up to render all materials lit exactly the screenshot posted

I made a photo studio blend which could serve as this. It's marked out with comments on how to use it, pretty confident *anyone* could use it - mostly drag-drop and use, and can output static and animation (turnaround cam).

I do think a standardized preview environment or settings is a good idea and I advise a studio environment to do so.
Note that texta is using some addons to change the render environment which may be invalidated here.
We should also agree on EEVEE as the rendering engine in Blender - I think we're all using this already, but just in case (Cycles is a raytracing engine, not realistic to what things will look like in Webaverse)


> standard way of matching Blender rendering to engine rendering.

This might be a ridiculous request, it might not - but if we have an equirectangular image capture of a preferred in-engine (Webaverse) environment, we can literally test things in Blender with that as our environment texture. It will not be perfect, but if you have a preferred test/lighting environment (that doesn't contain other light sources), we can do that.
From my understanding the current skybox etc is procedural, so I don't think this is possible. 


> arbitrary values during development.

See #1335. These are not arbitrary and importantly they're not a final asset either, which is why you're seeing them.  

https://github.com/webaverse/app/issues/1335#issuecomment-886596243

> It is inconsistent what the top level object is in these assets

In some cases this is due to a WIP being uploaded to drive as part of stand-up process, but this is understandable and can be improved.

I'd propose that artists should therefore, *where possible / appropriate*
- Compile final model in blend to single collection, parented to single copy/paste buffer compatible object
- Use agreed upon lighting environment(s) for WIP and screenshots (and display HDRI settings if appropriate)

**Comment by Vianvolaeus** [comment]
Quick note: environmental HDRIs can be used (and matched) in Substance, and all of the default ones in Blender are CC0 from HDRIHaven. I've been matching them up to the one I use in Blender for consistency already.

**Comment by Vianvolaeus** [comment]
Something in the minting environment in the FE isn't working correctly:


![image](https://user-images.githubusercontent.com/80061436/126993590-06bb7e77-52d9-4567-ab9c-983899b69b2e.png)

This is the Alpha Blend Mode Test model from the Khronos Group: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AlphaBlendModeTest/README.md

Opacity appears to not be working, but importantly the lighting appears to be *very* strong compared to what would be a normal lighting environment (a HDRI, for example)

There's also some odd level of 'saturation' occuring:

![image](https://user-images.githubusercontent.com/80061436/126994190-0c820e11-70bd-4bb4-86f7-5ad215daf40e.png)

**Comment by Vianvolaeus** [comment]
https://github.com/webaverse/app/issues/1116

**Comment by Vianvolaeus** [comment]
We probably want to block (non-baked) ambient occlusion, bloom, SSR and all other forms of post processing unless we can reliably recreate them in engine, which to the best of my knowledge, we can't.

**Comment by avaer** [comment]
> Models made of different parts should be parented to either their rig (armature object) or an Empty.

I agree.

> Rigged objects are consistent across the copy/paste buffer you are using to compile a scene. I'm not 100% on the Empty solution, (I am fairly certain it works, since sketchfab models converted to gltf etc use this method)

Yup it worked for me.

> I made a photo studio blend which could serve as this. It's marked out with comments on how to use it

Yeah, sorry, I should have used it. Can you link here posterity? That's the better call, though the problems I experienced were more on the source side than the destination.

> This might be a ridiculous request, it might not - but if we have an equirectangular image capture of a preferred in-engine (Webaverse) environment, we can literally test things in Blender with that as our environment texture. It will not be perfect, but if you have a preferred test/lighting environment (that doesn't contain other light sources), we can do that.
From my understanding the current skybox etc is procedural, so I don't think this is possible.

This should be driven by the artists so if you want to make that call, it would be on the engineers to implement it. We do have things like procedural sky, but I think for now we'd just use whatever HDRI the art team selects rather than trying to do that part dynamically. We can revisit this later.

Hopefully that makes this less ridiculous :D.

> https://github.com/webaverse/app/issues/1393#issuecomment-886689890

Awesome, thx for the test case!

> We probably want to block (non-baked) ambient occlusion, bloom, SSR and all other forms of post processing unless we can reliably recreate them in engine, which to the best of my knowledge, we can't.

Yup, not yet. But these are great ideas.

> Emissives won't be as obvious in that case and should probably be previewed in their own emissive pass render so it's clear what's emissive and what isn't.

Excellent observation. I made an issue for bloom: https://github.com/webaverse/app/issues/1398

**Comment by Vianvolaeus** [comment]
Apologies, I had a comment for this and thought i'd posted it:

> Can you link here posterity? (photo studio)

https://drive.google.com/drive/u/1/folders/1FfsGpsKYlB7zkA43OzrqFmDFoLgo6Jyk

I made a short video on using it as well, but it does have comments / instructions built in:

https://www.youtube.com/watch?v=dAM2RrfYWL8

It might be worth me revisiting this and polishing it up. It was originally made so we actually had an interesting scene to preview items for socials, etc for teaser content, but it can definitely work for other workflows. 


Default HDRI is the right call I think, since that can be transferred across pretty much any location for input / output of content. Although we're likely going to be in a solarpunk setting and likely a green field-ish location, we should probably use a studio lighting environment to avoid color influences. I'll test some we're available to redistro if needed (cc0)

Thanks for making the issues. I think Bloom is the more important one FWIW, since we can do some level of baked AO in gltf.
