### ISSUE TITLE
Contract upgrade/migtate pre-deploy wishlist

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1413]
* [ ] Get rid of a separate LAND NFT, and the single/multi metadata distinction
* [ ] Remove restriction that hashes are unique
* [ ] Rethink multi-mint, because it would no longer be enforced by hash sameness
* [ ] Implement transfer lock https://github.com/webaverse/app/issues/1412
* [ ] Support minting fees/minting windows
* [ ] Support royalties/transfer fees
* [ ] Support splits

**Comment by softwarebycl** [comment]
> Minting fees

Looking at the top existing NFT marketplaces, most take a fee on transactions rather than the mint

----------

[Rarible](https://gov.rarible.com/t/must-read-complete-guide-for-people-new-to-nft-eth-or-rarible/4002) - **5% of sale**
> Rarible takes a commission at the very end, it’s 2.5% on each end, so 5% of final sale price.

[Foundation](https://help.foundation.app/en/articles/4742888-a-complete-guide-to-listing-an-nft-for-auction) - **15% of sale**
> There will be a 15% service fee charged to the final sale price of your NFT, so make sure you take that into consideration when setting your reserve.

[OpenSea](https://docs.opensea.io/docs/frequently-asked-questions) - **2.5% of sale**
> OpenSea provides its marketplace infrastructure for free—it's entirely free to get started setting up a marketplace and using our platform. As compensation for this service, 2.5% of each sale will go to OpenSea.

[Superrare](https://superrare.com/about) - **3% of sale**
> There is a simple 3% transaction fee for all purchases, paid by the buyer.

[KnownOrigin](https://knownorigin.io/journal/platformupdate/making-a-secondary-marketplace) - **15% of first sale, 2.5% secondary**
> On the first or primary sale of a KnownOrigin artwork, 85% goes to the Artist, 15% goes to the commission fee. For a secondary sale (and all sales made after the first sale) 85% goes to the Seller, 12.5% goes to the Artist and finally, 2.5% goes to the commission fee.

**Comment by avaer** [comment]
Both minting and transfer fees feel important to have, added it to the list.

The minting fee is for a token sale and the secondary fees are for royalties.

**Comment by softwarebycl** [comment]
> Get rid of a separate LAND NFT

I think this is fine, there are other ways to specify which NFTs are "LAND" NFTs, can just be a whitelist.

> and the single/multi (hash-based) metadata distinction
> Remove restriction that hashes are unique
> Rethink multi-mint, because it would no longer be enforced by hash sameness

It looks like all of these go together.  It would be more ERC standard to go by tokenID rather than hash.

> Support minting fees/minting windows

What are you thinking here? Should it be a fixed fee in SILK? Updatable fee? What would minting windows look like?


> Support royalties/transfer fees

This should be something set by the original creator/minter as they're minting

**Comment by avaer** [comment]
> I think this is fine, there are other ways to specify which NFTs are "LAND" NFTs, can just be a whitelist.
It can be a secure metadata set which can only be set by the admin address, or contracts granted that permission (see minting windows).
> It looks like all of these go together. It would be more ERC standard to go by tokenID rather than hash.
We were already doing everything by tokenId, but hashes uniqueness was enforced across a set. I just don't think enforcing the hash adds anything to the user/collector/owner experience, the NFT is already unique and hashes could be gamed so easily anyway with small file edits.
> What are you thinking here? Should it be a fixed fee in SILK? Updatable fee? What would minting windows look like?
I think a second contract, which has mint permissions and metadata setting permissions, and sets a special flag/metadata that this is an NFT minted for this specific event -- which can be read to securely determine that fact in the future.
> This should be something set by the original creator/minter as they're minting
I agree, but it would have to be baked into the contract to work.

**Comment by madjin** [comment]
Showing my work with thoughts on fees:

- Notable that most take a fee on transactions rather than the mint
  - Once price is set, hard to change unless it goes lower
  - If we charge minting fees for season 1, we can adjust/remove in future season if it doesn't work out
- In terms of user experience, I don't want to pay double fees (silk + eth) to mint unless:
  - There's some kind of value add to minting via this contract such as:
    - Pays for decentralized storage (arweave + filecoin)
    - Placement in the virtual world
    - Generating a trading card and other formats
- How much SILK is in circulation for this season?
  - Capped based on planned drops and how much SILK gets packed into each NFT
    - It'd be interesting and probably safer to distribute SILK this way
    - SILK can later be used for governance (snapshot voting)
    - NFTs with packed FT help with price discovery of SILK
  - How does one acquire it?
    - Earning it through bounties and events
    - Buying packed NFTs
    - Burning / offering NFTs for tribute
    - Buying it from a LP
  
IMO it's fine to start with a flat initial minting fee (can remove if it doesn't work out) to atleast cover the costs of IPFS + arweave, and set a first sale fee of 10%. This should make it known during the minting process as something you can't change while you can adjust splits if you're collaborating with another artist. It will be perceived as a collaboration with Webaverse (which it is). Afterwords, there can be a royalty of 10% to the artist.

Hope this can be useful.

**Comment by madjin** [comment]
> @madjin Do we want allow split royalties? So on mint a minter can determine:
> 
> * royalty %
> * royalty address(es) to pay royalty out to on secondary sales
> 
> When you're minting you can specify 1 or more addresses to pay out the royalties to.
> 
> Should it be capped or it can be infinitely split across addresses?

IMO if there's more than 5-10 people involved they're better off setting up a multi-sig / DAO / fractionalizing NFTs and figuring it out from there. I think it should be capped to keep the UI/UX simple, cap to 10 people.

For reference, Cargo determined 15 addresses and up to 15% for royalty-splits is a good idea: https://docs.cargo.build/info/split-royalties#:~:text=Cargo%20allows%20creators%20to%20set,collection%20are%20eligible%20for%20royalties.&text=The%20maximum%20royalty%20fee%20is%2015%25.

Opensea allows for royalties up to 10%. The lower it is the better for secondary market liquidity. If we allow for too high a number, buyers might be trained to watch out for "gotchas" in every listing. I think up to 10% is good.

**Comment by madjin** [comment]
Some reading on royalties:

- https://eips.ethereum.org/EIPS/eip-2981
- https://www.gemini.com/blog/exploring-the-nft-royalty-standard-eip-2981
- https://manifoldxyz.substack.com/p/royalties-demystified-
  - https://github.com/manifoldxyz/royalty-registry-solidity
  
Useful reading on splits: https://dev.mirror.xyz/V_7Jp1hy_g8bz-J1B4Wb5KYSmj5Lt4W7q7cw0noxJsU

**Comment by softwarebycl** [comment]
> What are you thinking here? Should it be a fixed fee in SILK? Updatable fee? What would minting windows look like?

> avaer: I think a second contract, which has mint permissions and metadata setting permissions, and sets a special flag/metadata that this is an NFT minted for this specific event -- which can be read to securely determine that fact in the future.

@avaer the mint/metadata permissions are clear. What's fuzzy is: should this second contract only be usable the treasury address? 

Or are users minting these contracts and it is constrained by a specific timestamp window? (only mintable between x and y timestamp)

It's not 100% clear to me what a mint window is and how it will be used.

**Comment by madjin** [comment]
I assume this contract is related to dropstorms. Mint windows are the moment a drop starts people can mint. It's not usually time based like open auctions are, there's often a supply limit. In order to prevent insane gas wars one measure implemented was a cap of mints per address (usually up to 20). Another way to save on gas is here: https://twitter.com/richerd/status/1432755637440577538

To experience what the mint window is about, it's worth checking out a live drop: https://rarity.tools/upcoming

Tbh from my experience the flow currently sucks, tons of people trying to mint and if you don't pay 2-3x the mint fees in gas you prob won't get it.

**Comment by softwarebycl** [comment]
> Tbh from my experience the flow currently sucks, tons of people trying to mint and if you don't pay 2-3x the mint fees in gas you prob won't get it.

I can see those issues, it is a very gamed scenario where you have to hack your way to the front.

Is there a better way to do drops? Do we want to do the mint window or do them in a different way?

**Comment by madjin** [comment]
The current state of the art is whitelisting addresses based on something on-chain, such as a certain NFT. This is how Larva Labs / BAYC have done their drops. Atleast this way the most deserving addresses are able to mint first. POAPs would be a good NFT for such a thing.
