### ISSUE TITLE
Docs: add instructions for sidechain metamask

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1445]
new section for transferring and burning tokens under "Market"

**Comment by avaer** [comment]
Here is the call to make: https://github.com/webaverse/dashboard/blob/69af182d32c55f5399dc135fb3265e5f4f81ae39/webaverse/blockchain.js#L330

A button on the docs page should trigger this, or it could be a code snippet (but that is considered slightly insecure).

**Comment by softwarebycl** [comment]
Related to https://github.com/webaverse/webaverse.com/issues/11 -- we'll have a button to switch between mainnet/polygon/webaverse sidechain and will have the ability to use web3 functions (transfer, burning) on the webaverse.com website. 

It may be better for me to get that setup (it's a current priority), then screenshot and document how to do it there rather than code it into the docs.

**Comment by avaer** [comment]
> It may be better for me to get that setup (it's a current priority), then screenshot and document how to do it there rather than code it into the docs.

That's fine with me as long as there is a path there from the docs.
