### ISSUE TITLE
Art: Zone 0 City Placeholder Asset

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1659]
The city in Zone 0 needs a placeholder asset until we can get the procgen solution working.

We essentially need a volume that's textured with some geometry sticking out, like a city facade.

I'll get a concept working, then we just need it created for use in-engine and as a prop in environment renders. It only has to look good from a medium distance, and only needs an exterior shell.

**Comment by plankatron** [comment]
doing some geo nodes tests to get the basic city layout :
![city5](https://user-images.githubusercontent.com/5592454/141341362-6d2b8f71-badd-4392-bd4c-53faee105929.jpg)
next is a basic terrain blockout , was important to do a few tests with geo nodes since we will probably be using it for this type of thing more and more (first for blockout and eventually for final hq assets to be baked down into game assets)
