### ISSUE TITLE
Animations: jump cycle

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1664]
We need five jump cycle animations _targeted against the mixamo rig_. The animation format and names must _exactly_ match the animations here: https://github.com/webaverse/app/tree/master/public/animations

## Video explainer
https://www.youtube.com/watch?v=2QMiGRcmckU

## Animations list
* [x] Charge jump
* [x] Charge -> jump -> fall
* [x] Fall loop
* [ ] Downwards kick
* [x] Landing

## Notes
* Doesn't matter how long the animations are, it's easily adjusted.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/139517879-9e9aef6f-f78d-45a3-9c25-9f4477ef3f6b.mp4

**Comment by plankatron** [comment]
here are two tests i did and where i am currently at with the jump animation, main issue : 
because the hip bone is where the code controls player movement it is essentially a non moveable bone, this presents a very challenging situation ecpecially for an animation that requires the body to bend down , then back up, if you cannot animate the hip a lot of the jump animation will not come through. 

https://user-images.githubusercontent.com/5592454/139850656-ca69112d-f18f-4763-9b96-90cdddd6c76a.mp4


https://user-images.githubusercontent.com/5592454/139850632-8809e595-559a-44a9-abcc-8850d3fad7f7.mp4

**Comment by avaer** [comment]
The reason this looks bad is that the animation loop is manually curated by the engine for this jump case. Once we have the animations separated then we can do a first stab at integration. They should already look reasonable in blender however.

**Comment by plankatron** [comment]
here is a drive link to 4 of the 5 animations and a small breakdown , armature does not have extraneous bones and all bones are prefixed with mixamorig:

*note* there may be a bug in the fbx exporter that exports 1 extra frame, have not completely confirmed this but if you notice that, it is a bug in the fbx exporter
### charge_jump
* 29 frames 
* charge 0-10
* jump 10-29
### charge_jump_fall
* 96 frames
* charge 0-10
* jump 10-29
* fall 29-96
### fall_loop
* 96 frames
### landing
* 36 frames 
https://drive.google.com/drive/folders/1C4q2hhT-ihrQ_WHYZWKrMZmrnV-pLlEM

**Comment by GaladWarder** [comment]
We currently have no way to test unexpected component animations at all, so these will need to be tested by a dev
