### ISSUE TITLE
App: Drop hunter asymmetric arms

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1848]
![image](https://user-images.githubusercontent.com/6926057/143029264-327e8b02-c99b-4a6c-9f14-f1046f437156.png)

The real arm is lower than the robot arm. This causes subtle posing errors due to the lack of symmetric bones.

**Comment by avaer** [comment]
The shoulders and arms should have the same bone Y.

**Comment by Vianvolaeus** [comment]
> The shoulders and arms should have the same bone Y. 

Needs clarification - do you mean the pairs should have the same Y, or both arms and both shoulders should all share the same Y value. 

I presume this is right-handed Z-up orientation?

**Comment by Vianvolaeus** [comment]
I've taken a look at this in some detail now and have some findings. 

**a) VRoid models by default do not have symmetrical armatures on import (even though they should)**

A basic model with no changes imported to Blender results in an armature that does not have symmetry in it's it's transforms. (-not- pose) 

b) transforms may be being affected in Unity either by the humanoid rig definition step or on the forced t-posing on VMR export. 

It would appear that the asymmetry in the bones is referring to the bone transforms, rather than the initial pose transform. 

Asymmetry in the design itself makes this a great deal more difficult. 
Fixing the asymm on the transform level requires editing to the geometry itself to match, since it is a transform issue and not a posing issue - the bone transforms when symmetrized do not carry the vertex influence with it, so the geometry would have to be manually matched to the new bone position. 
We can match the robotic hand to the human hand to make this step a bit easier, since it is using 'floating' balljoints & fingers. 

I know for a fact that the robotic arm was modelled to the exact positioning of the initial armature / bone head & tails so it would be matched, so *somewhere* something has changed in those transforms. 😐


I'll make an extensive look at this tomorrow and see what's best angle of approach.

If you are blocked on the code with Scillia specifically, I would advise using a different model.

**Comment by avaer** [comment]
> Needs clarification - do you mean the pairs should have the same Y, or both arms and both shoulders should all share the same Y value.

Ideally the bone positions are mirrored around x, so applying the same transforms to the arms creates the same resulting pose. That is currently not the case and it is quite obvious in kalodokit posing and vr; putting up your hands to the same height will actually result in an unbalanced avatar with arms at different heights

> If you are blocked on the code with Scillia specifically, I would advise using a different model.

Yeah I am doing that for now, but it means I don’t know how well our own avatars are working.

**Comment by avaer** [comment]
> Asymmetry in the design itself makes this a great deal more difficult.
Fixing the asymm on the transform level requires editing to the geometry itself to match, since it is a transform issue and not a posing issue - the bone transforms when symmetrized do not carry the vertex influence with it, so the geometry would have to be manually matched to the new bone position.

Yeah sorry if it’s difficult. I think the geometry design is fine, but in the ideal version, the geometry remains the same while the inner bone geometry is mirrored and reweighted to still look correct. If that is not possible we can move the geometry.

The problem is not major but it is annoying enough that the features feel subtly broken.

**Comment by Vianvolaeus** [comment]
I've uploaded a version with fixed bones - for whatever reason, I cannot get this to export *with* visemes / springbones etc, so I'll have to circle back and properly debug and see what's going on in Unity, but it should serve as a test for the bone symmetry in kalidokit hopefully. 

https://drive.google.com/drive/folders/123HxmDoObG9s6kdRTQybLkxyiuSXZ9rv

**Comment by avaer** [comment]
Thank you, I checked and it looks like the arms are correct now.

![image](https://user-images.githubusercontent.com/6926057/143677404-c8537776-04d7-4f9e-bf87-d507d5210b20.png)

Will revert for now until we can fix the visemes.

**Comment by Vianvolaeus** [comment]
I've updated this again - outright replaced the non-viseme version. It should be in line with the old, pre-fixed armature version, copied the data over to match 👍 

Above link will take you to the updated variant

**Comment by Vianvolaeus** [comment]
Since this appears to be relevant to #1788 - I've noticed that by default VRoid models are asymmetrical on armature and geometry level. It's not noticeable visually, but the actual math is off for their bone positioning initally. Not sure if that's problematic? We can visually test just with a default export and see if it poses any issues.

**Comment by avaer** [comment]
Done.
