### ISSUE TITLE
app: crippling while walking

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2006]
After CCD update, The crippling of avatar has increased way too much  specially on uneven surfaces, areas with much hurdles and while climbing down the hills. More

https://user-images.githubusercontent.com/35926530/146073619-d1dbe94c-0dfe-4842-9011-1baa48f0e13d.mp4

https://user-images.githubusercontent.com/35926530/146073660-58391e99-b0a5-412d-b251-f5cd3e3132d0.mp4

https://user-images.githubusercontent.com/35926530/146073721-10e12067-d5c1-4dd7-857a-e1a2f00163c5.mp4

.

**Comment by avaer** [comment]
Hat does crippling refer to? The jumping?

**Comment by amnaarshed4224** [comment]
yes. While coming down the slopes and when hurdles come in the way. The jumping trigger, when happens much frequently, It feels like crippling.

**Comment by 0xmetabad** [comment]
This is the line to control the sensitivity in the character controller:

https://github.com/webaverse/app/blob/5b364e48e89916807d09398d60733eed64ac222e/character-physics.js#L164-L166

Some other ideas from Discord:

> gonnavis: I use raycast to add tolerance between land & air

> avaer: or we could increase the delay to falling
but better physics should be preferred
but one way to attempt to fix this in physics is to shift the character slightly down more if they are grounded
making them less likely to hop
but it might also cause a slipnslide effect

Also reporting this issue is seen in the silk fountains tunnels, which detracts from the magical experience:

https://user-images.githubusercontent.com/29695350/148236493-75cae11b-a216-46e9-83c1-a9a12b517a92.mp4

**Comment by avaer** [comment]
This is simply the character going to jump state when they are not touching the ground, since they are walking faster than gravity.

It can be fixed by:
1) gluing the character more to the ground using the character controller to push them down (breaks realism but more cartoon-correct)
2) Increase gravity to be higher, at least when grounded (not realistic but would fix the problem)
3) Decrease character move speed (not desirable for gameplay, doesn't fix running)
4) Let the character bounce like a ball but take longer to start falling, increasing the Wile E. Coyote effect, but it might pass under the radar

There are many other options but we can at least test these to see which one is best.
