### ISSUE TITLE
Arms sometimes go under the clothing

### ISSUE THREAD

**Issue by yaserOSource** [webaverse/app#2111]
![image](https://user-images.githubusercontent.com/51108458/147712738-b7e95b6e-3e18-44a6-a7fd-3ea9f39795f9.png)

Tested Latest master 0981889ee49a0447a7edeff18968ca3716367458

Seems to occur progressively

**Comment by avaer** [comment]
This model will not be used.

However, this is purely an interaction with the model and the animation used; it's not possible for us to cover all cases. The idle animation changed to be more dynamic and have hands closer to the body, so the model might be exhibiting more clipping now (and others may exprience less).

There are ways to hack around it but this seems one of the lower priorities to work on in the animations stack, since the animation still looks fine this way, while many others do not.

**Comment by ahadshams** [comment]
can we close this issue?
