### ISSUE TITLE
App: animation_url used to load .metaversefile in app, but NFT marketplaces will show as json then

### ISSUE THREAD

**Issue by softwarexyz** [webaverse/app#2129]
For loading NFTs from wallet in Webaverse, it looks like putting the path to the `.metaversefile` in the `animation_url` metadata field was decided on.

This will make it easy for Webaverse to pull NFTs from a user's wallet and load them into the world. The downside of this is that NFT marketplaces will then show json as the preview image.

I'm not sure if there is a better solution, but wanted to bring this up.

![animation](https://user-images.githubusercontent.com/29695350/147878824-535bed95-6a1b-4404-b83b-2d3a5592b570.PNG)

Note: that the NFTs are rendered using the `image` and not `animation_url` when outside of the specific asset detail's page, for example this is the `image` which links to a gif:

![cardlll](https://user-images.githubusercontent.com/29695350/147878879-ed810879-f3b0-43ab-adda-af24dd976faa.PNG)

**Comment by avaer** [comment]
> For loading NFTs from wallet in Webaverse, it looks like putting the path to the .metaversefile in the animation_url metadata field was decided on.

Putting `.metaversefile` into the token url itself is not the intended usage. Does some documentation say otherwise? (we should fix that)

`.metaversefile` is designed to be out of the way, in the same directory as the content you are trying to render. That is why it is a dotfile. If you point `animation_url` to a bare directory the `.metaversefile` should be auto picked up.

IMO we should just have `"metaverse_url": "https://path/to/.metaversefile or https://directory/containing/metaversefile/"`, but that handling needs to be implemented.

**Comment by 0xmetabad** [comment]
`metaverse_url` would work for me. I don't think this exists in the documentation currently, I asked in #dev channel in discord and was told it was `animation_url`. 

Was trying to figure out which field to use so that when someone connects their web3 wallet to Webaverse, they are able to load the `.metaversefile` into the world.

Since OpenSea uses `animation_url` to showcase the nft, it makes sense not to put the `.metaversefile` there since it would show as json ^.

I'm cool with whatever field will be used to load into webaverse, I think `animation_url` has been used since that is where most 3d nfts put their `glb`/etc.

Webaverse could look at an NFT and load it in based on a priority of:

1. Does it have a `metaverse_url`, load that in
2. If not, then `animation_url`
3. If not, then `image` or `image_data` (raw svg)

**Comment by avaer** [comment]
Yeah I think that's the right priority for keeping things opt-in and optimally compatible. It sounds like a small feature to implement that.
