### ISSUE TITLE
app: Text chat crashes

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2141]
Entering "ENTER" to text chat crashes the the game in the following scenes:
-Shadows
-Grid
-Prototype
-Forest
-Silk Fountains

https://user-images.githubusercontent.com/35926530/147973265-a9e33e7d-a4bd-467f-977b-d35c1c3deb5e.mp4

![1111](https://user-images.githubusercontent.com/35926530/147973238-1efa98e8-dc85-4d2b-9280-319eef051504.PNG)

**Comment by avaer** [comment]
Good catch, this error is in the update of some shadow map uniforms upload when rendering the side avatars scene.

It's is probably because the avatar diorama scene's outline mesh is stealing the world lights for itself, and the shadow maps are part of the lights. Therefore the shadow map seems like it is being "wasted" on the avatar pre-render, and the subsequent uniform update fails or something.

I think we can just update the code to not hijack the lights, and let the avatar scene have its own light set.
