### ISSUE TITLE
App: Create a list of working/non-working features

### ISSUE THREAD

**Issue by abeersaqib** [webaverse/app#2196]
**Bot**

* [x] Minting
* [x] Inventory
* [x] Transfer
* [x] Previews

**App Mainnet(Opensea)**

* [x] Minting
* [x] Inventory
* [x] Previews

**App Sidechain**

* [x] Minting
* [x] Inventory
* [x] Previews

**Comment by amnaarshed4224** [comment]
Discord Bot:
 Minting, inventory, transfer works fine.
 Previews have these issues:
 1-All the previews are in png format that limits the view of other frormats such as gifs, mp4,txt etc
 2-On mp4 preview, this err appears
 
![mp4preview err](https://user-images.githubusercontent.com/35926530/149209513-96de7b4d-218b-4585-acaa-28fe8f03a183.PNG)

3-On .txt, .rtf preview:

![txtpreview](https://user-images.githubusercontent.com/35926530/149209576-4eef54de-8349-42d1-a52b-7e16b8bdab6f.PNG)

**Comment by amnaarshed4224** [comment]
app mainnet and sidechain:
-The minting inside app doesn't works yet. (I am not sure if this feature is there or not)
-No previews of assets

![mainnet previwews discord](https://user-images.githubusercontent.com/35926530/149630424-3601480a-554b-4f98-93d7-05333a7aeb3c.PNG)

-The discord bot even shows assets which i am not owner of but were minted by me.

https://user-images.githubusercontent.com/35926530/149630445-0d0408c7-7444-4e79-9fd8-715203a25f47.mp4

![inventory](https://user-images.githubusercontent.com/35926530/149630436-b790abfb-b341-449f-90f2-db3b1cce0469.PNG)

-logging in through metamask after logging out of discord shows assets from previous discord.

https://user-images.githubusercontent.com/35926530/149630462-ef62eac5-01a3-4b65-92fd-99b8403a59b6.mp4


I will make seperate issues for the above mentiioned bugs. So that they may not go unnotced.
