### ISSUE TITLE
Naruto run animation has scale transforms

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2350]
The naruto run animation is violating the standard by having scale transforms on the animation.

```
$ node animations-baker.js
```

```
unknown track name naruto run.fbx VectorKeyframeTrack {
  name: 'mixamorigRightHandRing1.scale',
  times: Float32Array(2) [ 0, 0.4000000059604645 ],
  values: Float32Array(6) [
    0.9999999403953552,
    0.9999999403953552,
    1,
    0.9999999403953552,
    0.9999999403953552,
    1
  ],
  createInterpolant: [Function: InterpolantFactoryMethodLinear]
}
```

**Comment by plankatron** [comment]
Here are the Tests I did yesterday : 
- deleted all scale keyframes in "naruto\ run".fbx 
- recompiled animations.z , still getting scale errors 
- rename walking.fbx to "naruto\ run".fbx , recompile no errors 
- import walking.fbx into blender, notice scale keyframes in this animation also 
**recommendation** 
- try to retarget the animation to our rigify/fbx armature then export via our normal method to hopefully remove these errors 
- if that doesnt work , redo the animation from scratch

**Comment by avaer** [comment]
This is still not done.

**Comment by plankatron** [comment]
so today i keyframed the naruto run by hand, matching up the run of the original animation with our fbx export rig setup. had to do this because re-retargetting did not fix the problem.  much to my surprise the warnings still happens, i did not keyframe any scale into the animation, the problem is much deeper than that. 

i took another animation that was done for webaverse and replaced it with naruto run , it too has scale issues, if i import walking.fbx into blender (if you over-write naruto run with walking the warnings stop) and re-export it completely on defaults it too now has warnings about scale keyframes. 

i believe the main reason for this bug is the at least the fbx exporter and most likely the fbx importer as well.

**Comment by plankatron** [comment]
so today , i went through most of the steps that i had already tried but also with galad this helped to double check my testing methods and helped to re-inforce the idea that the exporter is forcing scale animation keyframes on export. 

galad also requested i try the same testing procedure in another modelling package, so modo was chosen. 
steps : 
-  import walking.fbx 
- tweak modo settings to only export animation
- export fbx from modo 
- recompile animations.z (cbor) 
result:
unknown track name naruto run.fbx VectorKeyframeTrack {
  name: 'mixamorigRightUpLeg.scale',
  times: Float32Array(27) [
                     0, 0.0416666679084301,
    0.0833333358168602,              0.125,
    0.1666666716337204, 0.2083333283662796,
                  0.25, 0.2916666567325592,
    0.3333333432674408,              0.375,
    0.4166666567325592, 0.4583333432674408,
                   0.5, 0.5416666865348816,
    0.5833333134651184,              0.625,
    0.6666666865348816, 0.7083333134651184,
                  0.75, 0.7916666865348816,
    0.8333333134651184,              0.875,
    0.9166666865348816, 0.9583333134651184,
                     1, 1.0416666269302368,
    1.0833333730697632
  ],
  values: Float32Array(81) [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1
  ],
  createInterpolant: [Function: InterpolantFactoryMethodLinear]
}

next step : figure out why the Mixamo animations aren't throwing the same error despite being FBX

**Comment by GaladWarder** [comment]
To add on to this, it seems that all exporters we have looked into/tried automatically include scale information into the file. This is regardless of if it is present in the animation itself. Blender has a series of options to adjust the types of scale applied, but no option to disable it. 
![image](https://user-images.githubusercontent.com/29031531/158473454-676e9abb-3ee3-41b2-b9d4-7ce77d13328e.png)


Further research has shown that scale information seems to be a part of the FBX format, which is why it is so weird that the Mixamo animations don't seem to have the same error.

**Comment by 0reo** [comment]
So i've found 2 possible way to get the fbx's exporting without throwing that warning, both of which are in the "Bake Animation" dropdown in the blender exporter
1. disable "Key all bones", "NLA Strips", and "All Actions", enable "Force Start/End Keying"
2. disable "Key all bones" and "Force Start/End Keying", enable "NLA Strips" and "All Actions"

Doing either of those removes the warning when running the animation baker, but trying to run the animation in game caused a crash due to missing tracks.  Throwing the naruto run animation into a try block allows the animation to run correctly, and the following tracks are identified as missing
```
mixamorigRightHandMiddle1.quaternion
mixamorigRightHandMiddle2.quaternion
mixamorigRightHandMiddle3.quaternion
mixamorigRightHandThumb1.quaternion
mixamorigRightHandThumb2.quaternion
mixamorigRightHandThumb3.quaternion
mixamorigRightHandIndex1.quaternion
mixamorigRightHandIndex2.quaternion
mixamorigRightHandIndex3.quaternion
mixamorigRightHandRing1.quaternion
mixamorigRightHandRing2.quaternion
mixamorigRightHandRing3.quaternion
mixamorigRightHandPinky1.quaternion
mixamorigRightHandPinky2.quaternion
mixamorigRightHandPinky3.quaternion
mixamorigLeftHandMiddle1.quaternion
mixamorigLeftHandMiddle2.quaternion
mixamorigLeftHandMiddle3.quaternion
mixamorigLeftHandThumb1.quaternion
mixamorigLeftHandThumb2.quaternion
mixamorigLeftHandThumb3.quaternion
mixamorigLeftHandIndex1.quaternion
mixamorigLeftHandIndex2.quaternion
mixamorigLeftHandIndex3.quaternion
mixamorigLeftHandRing1.quaternion
mixamorigLeftHandRing2.quaternion
mixamorigLeftHandRing3.quaternion
mixamorigLeftHandPinky1.quaternion
mixamorigLeftHandPinky2.quaternion
mixamorigLeftHandPinky3.quaternion
```
this leads me to believe that blender's export is adding in scaling data when baking because it thinks it's "missing".  2 possible solutions come to mind
1. ensure the above mentioned animation tracks have some type of value when exporting using the above settings, to prevent crashes
2. allow in code for tracks to be undefined, and throw a warning when an expected track is missing

**Comment by avaer** [comment]
> next step: figure out why the Mixamo animations aren't throwing the same error despite being FBX

The next step seems to be to give up on that file. It seems like it would have taken no more than a few hours to remake it, even if we are literally pasting keyframe numbers to a working mixamo.

Sometimes tools have bugs and there's no point trying to get around them.

**Comment by avaer** [comment]
Failing that I'm ok with just adding to our code a loop that checks that if there is a scale it must be all = `1`, and then thrown away. (if that is violated we should crash because there is currently no way we can render such an animation).

**Comment by avaer** [comment]
This is a simple a tooling failure that can be worked around. Let's not spend months on it.

**Comment by 0reo** [comment]
> Failing that I'm ok with just adding to our code a loop that checks that if there is a scale, it must be all = `1`, and then it can be thrown away (if that requirement is violated we should crash because there is currently no way we can render such an animation).

blender does seem to allow you to set a scale of `1`(or whatever we'd choose) to all transforms, which should satisfy this.  i can update the baker code to support this

**Comment by avaer** [comment]
Please. Just validate it's all 1, and then throw it out if that's the case.
