### ISSUE TITLE
app: Avatar unable to move in latest master

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2372]
In latest master, The avatar movement is disabled. It isnt able to move any where. Throws this error.

![latesterr](https://user-images.githubusercontent.com/35926530/154363082-9a7a6fbe-51d0-41bb-bcca-dfbd80232860.PNG)

https://user-images.githubusercontent.com/35926530/154363131-357b8a89-8ca1-4dfe-952f-cc19ccda7a43.mp4

**Comment by amnaarshed4224** [comment]
![physixcs](https://user-images.githubusercontent.com/35926530/154364478-414abe8f-c0d4-42e2-a97c-dda6138abdc9.PNG)

**Comment by rob-webaverse** [comment]
I've created a new "stable" branch and reverted it to the last commit before this problem shows up: https://github.com/webaverse/app/commit/10d8448d8677d81bcbcbf0f0a962f0c1948528b0 . And I've changed the codepipeline for app.weba to update on "stable" instead of "master", so app.weba no longer reflects this problem.

**Comment by amnaarshed4224** [comment]
Reverted!
