### ISSUE TITLE
app: Bow/Pistol issues

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2423]
1- The aim for both pistol and bow needs to be fixed. The shot is not shot at the aimed spot.

https://user-images.githubusercontent.com/35926530/155197285-d1f226b1-fe83-442f-a9d4-f18e1f6c1db9.mp4

2-The damage mesh in case of bows arrows seems odd right now. There should be something done with the damage meshes because when the object vanishes after multiple fires, it looks odd.

https://user-images.githubusercontent.com/35926530/155197376-26142cdf-8174-48c8-b891-1df9732f6129.mp4

https://user-images.githubusercontent.com/35926530/155197420-fc7ad87d-edf9-478c-a823-53557b85b6f0.mp4

3-The aim point in non-First person view does lets us see where the shot is being shot.

https://user-images.githubusercontent.com/35926530/155197411-b43720ca-77a9-4f38-9fd1-7f99618adfd2.mp4

**Comment by avaer** [comment]
The reason for these inaccuracies is that the shooting is not based on the reticle, it's based on the kinematics of the avatar. IMO we should continue to do it that way, since that is how it will work in XR.

However, we could fix the kinematics to be more accurate to the reticle. That is mostly deep animations work.

**Comment by amnaarshed4224** [comment]
This also appears in treehouse.scn, related to bow.

![7](https://user-images.githubusercontent.com/35926530/155571020-0dccda43-668c-43cb-9167-57a40d74b741.PNG)

**Comment by avaer** [comment]
☝️ no that is not related to the bow.
