### ISSUE TITLE
app: Master is crashing in darkness.scn

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2436]
Master is crashing on on switching to darkness.scn

![4](https://user-images.githubusercontent.com/35926530/155566556-099b9194-4d78-480f-9363-0fe92766b166.PNG)
![5](https://user-images.githubusercontent.com/35926530/155567354-e56ad45f-6ce7-4a7f-9600-78bb82aeef06.PNG)
![6](https://user-images.githubusercontent.com/35926530/155567360-6f4df19a-eb07-4875-8bc2-cc6265c4b34b.PNG)

**Comment by avaer** [comment]
Thanks!

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/155600953-2a6f563a-bc86-47c0-9741-eeca011a97bf.png)

I removed a tracked app check in this code because it didn't make sense to me and it still doesn't. However, it is causing the crash.

The app in question is a `light`.

However I don't understand how the app can exist without the tracked app existing. Will keep looking.

**Comment by avaer** [comment]
Ok I see, we don't want the rendersettings to be pushing tracked apps, but only transient apps. That is, loading the world should not cause multiplayer data to be pushed. I think the original check was valid.

Will add a comment to that effect, this is my bad.
