### ISSUE TITLE
app:Cors error while trying to drag and drop objecs

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2438]
These cors errors appear oftenly when we try to drag and drop objects or metaversefiles.
Currently i have been handling it by installing a plugin named moesaf CORS, But it appears to cause some other issues and errors that don't occur without it.

![cors](https://user-images.githubusercontent.com/35926530/155570737-a2b8f969-edd1-4471-ba77-1939dc820322.PNG)

**Comment by avaer** [comment]
> Currently i have been handling it by installing a plugin named moesaf CORS, But it appears to cause some other issues and errors that don't occur without it.

You should not do that.

This is because that "kitchen" app is not properly published on Github. Most likely it did not follow the standard GitHub rule were you must have a `.nojekyll` file to publish dotfiles, like `.metaversefile`.

The author of https://github.com/ahmad-zfr/kitchen did not follow GitHub publishing instructions.

**Comment by avaer** [comment]
> These cors errors appear oftenly when we try to drag and drop objects or metaversefiles.

Can you point to the other Github issues?

**Comment by amnaarshed4224** [comment]
I have just realized, The Error occurs when using Direct Download url of .glb file instead of using GitHub pages url.
With GH pages url, it works fine.
