### ISSUE TITLE
Dash not moving the character forward in tanabata city

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3072]
The dash is only pulling the camera back and the avatar is not moving.

https://user-images.githubusercontent.com/104460803/170514476-38776cdc-586b-43f7-b5cf-533b871b3e74.mp4

**Comment by alisaad673** [comment]
Please make sure that there is no error in console before an issue like this appears. As most of the times, such errors are due to some other previous bug. Like in this example, You have the destroy_material error in console that appears when you try to change a scn after equipping or unequipping any item. That causes various bugs related to scenes functionality.
