### ISSUE TITLE
UI: Unable to scroll / click NFTs in sidebar

### ISSUE THREAD

**Issue by madjin** [webaverse/app#3074]
When signing in via metamask I am unable to scroll up n down on my inventory on the right sidebar nor click any of my NFTs to spawn in-world

**Comment by mwmwmw** [comment]
I looked into this issue for a few minutes. This issue is due to pointer events being ignored in the CSS on the tabs. 

If I disable the pointer-events code, I can interact with the NFTs. Nothing happens when I click/drag/drop, but that might be due to the pointer-events being blocked by tabs. 

I think at least some of this issue is just some CSS that is interfering with the list.

Working on a fix. 

![image](https://user-images.githubusercontent.com/889851/170799021-980142e9-e56c-4052-b172-b32615c05bf0.png)
