### ISSUE TITLE
app crashes while trying to edit certain objects in world tokens

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3096]
Right now, After theo's fix to world tokens issue, Most of the items work fine(we are able to edit them), But certain items gets the app crashed when we click on them.Throws these errors. For example, skybox, application/light in street scn, plaza in plaza.scn.

![world1](https://user-images.githubusercontent.com/35926530/171252388-a3ce983a-8a83-4d20-a728-7abb85e34f41.PNG)
![world2](https://user-images.githubusercontent.com/35926530/171252395-be4d6203-6b00-4eaa-94c5-4b34b2986c31.PNG)

https://user-images.githubusercontent.com/35926530/171255128-4fbe7733-3725-447e-973a-0039da27cb16.mp4

**Comment by mwmwmw** [comment]
@alisaad673 This was actually two bugs in one. 

When you selected items without physics objects it would crash because it had hardcoded the objects to retrieve from the zero indexes. 

If you selected an object with no physics it would crash. If you selected an object with more than one physics object, it would only apply scale changes to the first one.

**Comment by alisaad673** [comment]
Hey @mwmwmw The fix for this has been merged in z-targetting branch. Do we need to add it to master too right?
