### ISSUE TITLE
Claims box throwing sword in case sword is dropped while being used

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3429]
If we open the claims box after we have dropped a sword while we were using it, It yields a sword along with silk. 
Apparently, the sword that appears in the claims box, is the same which we dropped earlier. Happens with the silsword too.
Related: https://github.com/webaverse/app/issues/3428

https://user-images.githubusercontent.com/35926530/181915620-b9b53335-6744-4e32-b1da-a83469933016.mp4

**Comment by patriboz** [comment]
This fix https://github.com/webaverse/app/pull/3453/commits/d7bead37723bd41575fe0c4a067d2a5ec2491c25 will prevent the chest from throwing weapons out, but I figured the issue is more complex. When I open the chest first and leave the silk on the ground and then pick up a sword, the silk is teleported onto me. I tried to fix this as well today, but not finished yet.

**Comment by patriboz** [comment]
https://user-images.githubusercontent.com/49231818/183097973-8076a747-cafd-4852-930f-df2e32e40674.mp4

**Comment by patriboz** [comment]
This should be fixed with: https://github.com/webaverse/app/pull/3453

**Comment by alisaad673** [comment]
Fixed: https://github.com/webaverse/app/pull/3526
