### ISSUE TITLE
Avatar slides while in use action

### ISSUE THREAD

**Issue by avaer** [webaverse/app#3560]
When picking up items we add the `use` action to the avatar, but if you are walking while you do it the avatar will slide along the floor.

Similar to https://github.com/webaverse/app/pull/3558, I think this needs to be fixed in the avatar system.

**Comment by gonnavis** [comment]
Hello @avaer , I think you mean `activate` action instead of `use` action ?

And I think when activating, we can't blend moving, because of we can't activate/pick up an item far away from us, especially when running.
So I tried to "Disable moving while doing activate." in this PR https://github.com/webaverse/app/pull/3562 , is it ok?

**Comment by gonnavis** [comment]
Second try https://github.com/webaverse/app/pull/3597

**Comment by alisaad673** [comment]
Fixed
