### ISSUE TITLE
FE: Help widget to Discord

### ISSUE THREAD

**Issue by avaer** [webaverse/app#511]
We should make a bottom-right widget with a person's face, linked to Discord.

**Comment by chrislatorres** [comment]
this could work https://widgetbot.io/

![chbot2](https://user-images.githubusercontent.com/29695350/104094288-962a8980-5255-11eb-8088-2f408f63c8d7.PNG)
![chbot1](https://user-images.githubusercontent.com/29695350/104094289-962a8980-5255-11eb-9d3f-a24a802dcbef.PNG)

**Comment by chrislatorres** [comment]
reasons why this one (widgetbot) is not great:
- requires name input
- brave shields block it
- spotty updating

**Comment by chrislatorres** [comment]
There isn't any good out-of-the-box solutions that easily plug in with Discord other than widgetbot, which is not great (https://github.com/webaverse/app/issues/511#issuecomment-757331173)

There are some that do not plug into Discord that are commonly used:
- intercom
- tawk.to
- crisp.chat

otherwise the alternative is creating one from scratch and integrating it into Webaverse Discord bot

**Comment by chrislatorres** [comment]
Instead of doing this chat box, we should just make it smooth to get into the Webaverse discord #help channel. We

The reason why is because the overall user experience is tied to having a Discord account (discord bot wallet + login to world/FE via Discord)

**Comment by chrislatorres** [comment]
I think we could do this best by getting people into a #help channel in Discord. There's a lot more useful help we can supply by having people logged into their Discord accounts, since that's the tie to the Discord bot / easy logins to the world, etc.

**Comment by avaer** [comment]
Hm that might be a good point, the first step in the funnel is probably to get them to join Discord if they aren't.

If they're not willing to log into Discord there is probably not much for them in the product.
