### ISSUE TITLE
Sittables

### ISSUE THREAD

**Issue by avaer** [webaverse/app#65]

**Comment by madjin** [comment]
Sittables have since been added in https://docs.webaverse.com/docs/create/mounts

![image](https://user-images.githubusercontent.com/32600939/121790371-c384b600-cbac-11eb-8945-dfbf726f8c69.png)

![image](https://user-images.githubusercontent.com/32600939/121790378-d0a1a500-cbac-11eb-8b4f-16473f39e00b.png)

![image](https://user-images.githubusercontent.com/32600939/121790394-06468e00-cbad-11eb-8cd5-f4a766372e78.png)
