### ISSUE TITLE
Editaverse: Missing assets / custom upload

### ISSUE THREAD

**Issue by madjin** [webaverse/app#818]
I noticed we can't upload custom assets to editaverse which is when I realized many categories of assets are missing (see pictures).

![image](https://user-images.githubusercontent.com/32600939/107465050-57b71180-6b16-11eb-991d-b4e4b4466070.png)

![image](https://user-images.githubusercontent.com/32600939/107465085-6f8e9580-6b16-11eb-9c28-4caa4e3e39e5.png)

**Comment by avaer** [comment]
Do we need API keys for these?

**Comment by chrislatorres** [comment]
Out of the box, all of this requires Hubs Cloud. I added a cors proxy to make some of these existing api calls work. 

Since we just export a glb, I don't think a lot of those Hubs scene components work. The custom upload for Spoke uses the Hubs Cloud, which saves those items to your Hubs Cloud/Spoke account for re-using later on.

**Comment by avaer** [comment]
Is it reconfigurable to use a different backend or is it pretty baked in?

**Comment by avaer** [comment]
If it is easy to add support for these other APIs by providing a key we should do it. Otherwise we should label this a backburner issue.

**Comment by madjin** [comment]
In the meantime we can add in some warning labels about the current missing functionality and a link to the Discord.

**Comment by chrislatorres** [comment]
We'll need to runs a Hubs Cloud instance to make this work. I'm going to label this as a backburner issue for now.
