### ISSUE TITLE
Backend: index/mirror/cache NFT data

### ISSUE THREAD

**Issue by avaer** [webaverse/app#856]
This issue is to generally handle the case of the frontend asset loading being slow.

The first part is that the preview images are slow (https://github.com/webaverse/app/issues/937).

The larger issue is that hitting the backend will currently read the blockchain. This is far too slow, because it usually requires multiple web3 requests to resolve to find NFT data.

Instead we should mirror all of the NFTs in a local dynamodb. 

Table:
```
sidechain-cache
Primary Key
id: String
```

**Comment by shawticus** [comment]
My suggestion that we are pushing forward is to modify the _getChainNft() to pre-check the dynamodb and return that, and send from the chain and update to db otherwise.
https://github.com/webaverse/api-backend/blob/9710d1fe01a680cdecfb930ab9175fe3f856f5ad/index.js#L1509

We'll still need to handle cache invalidation -- whenever the metadata is changed we'll need to update the db copy.
This will probably need to happen around here:
https://github.com/webaverse/api-backend/blob/6c185c73771b0e3b6f8a4b48b1ea69fc9bc5ff55/events-manager.js#L37
on these events:
`A.${WebaverseNFT.slice(2)}.WebaverseNFT.Withdraw`,
`A.${WebaverseNFT.slice(2)}.WebaverseNFT.Deposit`,
`A.${WebaverseNFT.slice(2)}.WebaverseNFT.MetadataChanged`,

**Comment by soulofmischief** [comment]
[`getPastEvents`](https://github.com/webaverse/api-backend/blob/8921d4c6db4a8527864e1ced188c96dd1ee095e1/cache.js#L98) is only picking up test mints like https://webaverse.com/assets/70, and they are missing most properties such as name, hash, ext and thus can't be cached.

Visiting https://tokens.webaverse.com/70 seems to resolve properly however, and [missing items are cached at this point](https://github.com/webaverse/api-backend/blob/8921d4c6db4a8527864e1ced188c96dd1ee095e1/index.js#L1640).

Otherwise most things are in place. Just stuck on cache invalidation because I can't seem to pick up the right events... Still looking. Thought I might have to use a specific contract, but `mainnet`, `mainnetsidechain` and `rinkeby` all give me the same results and `rinkebysidechain` gives an error. Not sure what the problem is yet.

**Comment by soulofmischief** [comment]
Ok. Found the right combination of contracts. I think it's all working.

**Comment by soulofmischief** [comment]
What's the best way to test events locally? I want to know that `events.allEvents` is working correctly.

**Comment by avaer** [comment]
You can listen to the sidechain ethereum nodes with S3, and then mint something. If you get the event, you know it's working.
