### ISSUE TITLE
ART: Prepare VRM avatars

### ISSUE THREAD

**Issue by shawticus** [webaverse/app#952]
We need to prepare a set of avatars for use in various capacities (in the world, promo materials, etc)

- Finish retexturing grey/yellow blue haired avatar
- retexture this one in a similar vein
https://hub.vroid.com/en/characters/9207116467873281386/models/2185787635578698415
- make sure characters have correct blendshapes (add if they don't)
- Plan other characters to add

References / inspiration:
https://hub.vroid.com/en/characters/3584359917051256331/models/5266838771505974684
https://hub.vroid.com/en/characters/5085524921842461136/models/2424900380462737064
https://hub.vroid.com/en/characters/336613518066779622/models/1645164713922268056
https://hub.vroid.com/en/characters/2857439350158494880/models/1256873476146834700
https://hub.vroid.com/en/characters/8091126400221849531/models/8795658192289288726
https://hub.vroid.com/en/characters/4446294434109815917/models/2504812665384570732
https://hub.vroid.com/en/characters/3036280241120217805/models/7699850259946557259
https://hub.vroid.com/en/characters/3582109135767760832/models/3051291826713567650
https://hub.vroid.com/en/characters/3857595944590487665/models/265693881831429600
https://hub.vroid.com/en/characters/4801228612599121667/models/688436609169640890

VRM emotions
- angry
- happy
- funny
- sad
- scared

**Comment by avaer** [comment]
GDrive where we keep models: https://drive.google.com/drive/folders/1FeGV-BvdHAdkk7yZ3c0sseclRARhVIBw

**Comment by avaer** [comment]
For `gear.vrm`, it is missing eye bones and visemes.

The artist was less experienced when they made `gear.vrm` so they made similar avatars since with much higher quality. Unfortunately they also deviate from the style, but perhaps copy pasting parts can work. E.g. they can be used to get visemes on a new head.

https://booth.pm/en/items/1143753
https://booth.pm/en/items/1475849
https://booth.pm/en/items/1244494

I have all of these and they are in the GDrive.

**Comment by madjin** [comment]
Eyes and visemes work, although the materials are poorly optimized.

![image](https://user-images.githubusercontent.com/32600939/111258021-63946880-85d9-11eb-9856-fc0dbcbac920.png)
