### ISSUE TITLE
Avatars: validate/remake/retexture

### ISSUE THREAD

**Issue by avaer** [webaverse/app#994]
## Part 1
We need to make sure we are allowed to use the following avatars, since we are targeting them as nfts:

* `gear.vrm` (https://booth.pm/en/items/1024547)
* https://hub.vroid.com/en/characters/8171135067054409405/models/1189318216410191025
* https://booth.pm/en/items/1880254
* https://hub.vroid.com/en/characters/4755472098203122209/models/8732392610956747100

If they cannot be used then we will need to remake them.

## Part 2
In either case, once we have usable avatars, they should be retextured with an alternate style; something like this, with a sharp dual tone.

https://hub.vroid.com/en/characters/1494477447257664251/models/785675084771217080

It might require re-uving if the uvs are too low resolution.

**Comment by avaer** [comment]
The avatars are found here in our gdrive: https://drive.google.com/drive/u/2/folders/1FeGV-BvdHAdkk7yZ3c0sseclRARhVIBw

Jin should be able to give access.

**Comment by Vianvolaeus** [comment]
> In either case, once we have usable avatars, they should be retextured with an alternate style; something like this, with a sharp dual tone.
> 
> https://hub.vroid.com/en/characters/1494477447257664251/models/785675084771217080

Working on some dither and halftone processors for the texturing process that should make this kind of thing possible,  as well as the PBR baker and Toon baker for processing different content workflows like this

**Comment by Vianvolaeus** [comment]
Picking this up once the hoverboard starter set is finished.

-  https://hub.vroid.com/en/characters/8171135067054409405/models/1189318216410191025

Usage rights mean this one cannot be used, will need redux

- https://booth.pm/en/items/1880254
Redistribution not allowed, can't use this one as a default or publicly available.
I imagine the 'usage when cloning is possible' is in respect to systems like VRchat's Public Avatar system / cloning.
This would nullify us being able to use it as a default avatar, but we *can* use it in the trailer.

It is a really nicely made avatar otherwise, I've tested this one out. 

 - https://hub.vroid.com/en/characters/4755472098203122209/models/8732392610956747100
 
 This is using copyrighted parts, we definitely can't use this 😅
 
 I can do the bases through VRoid so we've got a consistent baseline for the armature and style, then add additional props and items later. 
 
 This also means we'll have access to the source layers and textures - will be easier to iterate alternate styles

**Comment by avaer** [comment]
Whichever avatars we use in the trailer, we'll want rights to use them in all contexts. If that means we need to remake then I think it is fine to spend that time.

**Comment by Vianvolaeus** [comment]
Agreed, if we're appealing to people with a focus on the avatars, then actually having access to what's displayed is important. 

I know how to recreate the effect of those floating mecha parts - messed with something similar on a personal projoect over the weekend.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/120228363-f035e680-c218-11eb-9b46-34e0e0920362.png)

Feedback from avaer:

4. eyes bigger and closer together? could also use more distinguishing features unique from others. what about freckling?
3. could be younger sibling to one of the other ones, in which case you need to think about how it's a foil. this one seems the most adventurous to me, so represents causing trouble but moving actions forward. the foil could be...
1. which is I think the best fleshed out, it's just fashionable, opinionated, reserved, at odds with 3.
2. I think a downgrade from the original, since it doesn't have any elaborate parts that make it stand out (like weird doc octo arms)

**Comment by Vianvolaeus** [comment]
Not sure what you mean in regards to the numbers, @madjin? are these feedback notes for the originals, or direction for the alternates? There's overlap in the numbers 😅

**Comment by Vianvolaeus** [comment]
Following on from meeting y/day, begun work on finalised details.

4 needed a couple of defining changes that ideally don't conflict with a wearable system or break the silhouette and design too much.

Some quick concepts were being done internally and I've settled on goggles being a good start - adds to the work / engineer aesthetic without breaking shapes too much.

This, combined with a tool belt/ backpack, etc as well as some texture changes, will be a good avenue, I think. 

Note - they could/can toggle on and off with a simple rotation of the entire object itself. Really simple stuff.

![image](https://user-images.githubusercontent.com/80061436/120838225-7a56b580-c55f-11eb-8418-c1e7b74aa267.png)

**Comment by Vianvolaeus** [comment]
Citrine UV issue is fixed. 

Made a multitool / kitbashed junker wrench for Citrine. It has similar emissive functions to the 'Megasword' that I recently made:

![image](https://user-images.githubusercontent.com/80061436/121367641-5fef5400-c932-11eb-9c5c-fb5b3219eb18.png)

Fits the utility aspect of the character, respects color scheme and theming etc. The emissive colors can be changed, i'm not 100% on these since they're quite similar to the other one.

**Comment by Vianvolaeus** [comment]
Been doing some experimentation with Kanji rework.

I think this is going into a different direction that's not too edgy or violent, imposing, etc: 
![image](https://user-images.githubusercontent.com/80061436/121368043-af358480-c932-11eb-90ce-e86b4d5a1e34.png)

I think a singular piece of chunky, obvious, oversized tech is a good way to go - 
![image](https://user-images.githubusercontent.com/80061436/121368267-da1fd880-c932-11eb-9ec9-5d8f90b7e35d.png)

I have two ideas: 

Large shoulder mounted piece - could have a few functions, but I like the idea of a large tech tower shield - 

![image](https://user-images.githubusercontent.com/80061436/121368327-e73cc780-c932-11eb-8feb-5995c3b10be2.png)

or it could be mounted lower and be more of an iconographic weapon / tool - eg a retractable tonfa weapon.
This is an incredibly rough concept just for visualising:

![image](https://user-images.githubusercontent.com/80061436/121368980-63370f80-c933-11eb-9cc4-78463b9c16bd.png)

It has the edgy factor of being a retractable weapon without the associated lethality (ie hiddenblade, claws, etc)

**Comment by Vianvolaeus** [comment]
I think blunt / non-lethal is something we may want to explore some aspect, even if it is not for this character in particular. Right now we have a lot of large, very over-the-top ultra lethal weapons - the contrast of something basic like this could serve a character well somewhere

**Comment by Vianvolaeus** [comment]
Shilo's jacket has been stripped back and i've thrown some geometric designs at it based from the shirt. 

There's probably more we can play with for color here, but I've stuck with the magenta for now: 
![image](https://user-images.githubusercontent.com/80061436/121371918-d0e43b00-c935-11eb-87a8-12f676b9dfd2.png)

**Comment by Vianvolaeus** [comment]
We do have an alternative color iris for Kanji - there's been some discrepancies with previews from Substance and the actual .blend - that's my fault.

![image](https://user-images.githubusercontent.com/80061436/121373034-a8107580-c936-11eb-91b3-df997ee5e343.png)

A change like this could be reserved for the alternative super versions.

**Comment by Vianvolaeus** [comment]
Long coat has a couple of texture variants. 
There's a good amount of open space on the back for something like an iconic decal or logo. In the preview we have a placeholder. 

![image](https://user-images.githubusercontent.com/80061436/121407732-87a4e300-c957-11eb-84a0-7dcdf603bf56.png)

**Comment by Vianvolaeus** [comment]
Backpack for Citrine made. Will need some fitting to the model to avoid clipping (will make a simple rig). Can be scaled as needed / appropriate. 

![image](https://user-images.githubusercontent.com/80061436/121733204-1bf37f00-caeb-11eb-9347-815415884792.png)
![image](https://user-images.githubusercontent.com/80061436/121733849-ec914200-caeb-11eb-918f-032ab0ee663d.png)
![image](https://user-images.githubusercontent.com/80061436/121733866-f024c900-caeb-11eb-968d-36893ee6cbde.png)
![image](https://user-images.githubusercontent.com/80061436/121734046-24988500-caec-11eb-9ddc-a9ee83088b5d.png)

**Comment by Vianvolaeus** [comment]
Kanji has a singular piece of tech now that can be animated as a weapon.

I was trying to combine the traditional aesthetic with a bit of techy flair, while keeping it non-lethal to avoid it being too imposing or scary: 

![image](https://user-images.githubusercontent.com/80061436/122278408-c51ce980-cede-11eb-8744-adf7d0774ab6.png)

I've made a testing animation here - i'm sure texta can blow it out of the water, but the tools should be there to do so: 

![ezgif com-gif-maker (100)](https://user-images.githubusercontent.com/80061436/122278376-be8e7200-cede-11eb-9913-22bf19b97b6a.gif)
